/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import {
  actionForCopy,
  actionForCut,
  actionForDelete,
  actionForPaste,
  actionForRedo,
  actionForSelectAll,
  actionForUndo,
  separator1,
  separator2,
} from "./operation-system-actions.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(actionForCopy);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(actionForCut);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(actionForDelete);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(actionForPaste);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(actionForRedo);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(actionForSelectAll);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(actionForUndo);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(separator1);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(separator2);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
