/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import endpointSlicesRouteInjectable from "./endpoint-slices-route.injectable";
import navigateToEndpointSlicesInjectable from "./navigate-to-endpoint-slices.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(endpointSlicesRouteInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(navigateToEndpointSlicesInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
