/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file imports and registers all injectables from subdirectories.
 * This replaces the webpack-based auto-registration system.
 */

import { registerInjectables as registerCreateReleaseInjectables } from "./create-release/register-injectables";
import { registerInjectables as registerDeleteReleaseInjectables } from "./delete-release/register-injectables";
import { registerInjectables as registerDialogInjectables } from "./dialog/register-injectables";
import helmChartRepoInjectable from "./helm-chart-repo.injectable";
import helmReleasesRouteComponentInjectable from "./helm-releases-route-component.injectable";
import helmReleasesRouteParametersInjectable from "./helm-releases-route-parameters.injectable";
import { registerInjectables as registerReleaseDetailsInjectables } from "./release-details/register-injectables";
import releaseSecretsInjectable from "./release-secrets.injectable";
import releasesInjectable from "./releases.injectable";
import removableReleasesInjectable from "./removable-releases.injectable";
import { registerInjectables as registerRollbackReleaseInjectables } from "./rollback-release/register-injectables";
import helmReleasesSidebarItemInjectable from "./sidebar-item.injectable";
import { registerInjectables as registerUpdateReleaseInjectables } from "./update-release/register-injectables";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(helmChartRepoInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(helmReleasesRouteComponentInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(helmReleasesRouteParametersInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(helmReleasesSidebarItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(releaseSecretsInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(releasesInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(removableReleasesInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerCreateReleaseInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerDeleteReleaseInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerDialogInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerReleaseDetailsInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerRollbackReleaseInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerUpdateReleaseInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
