/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import handleExtensionSchemeInjectable from "./handle-extension-scheme.injectable";
import registerExtensionSchemeAsPrivilegedInjectable from "./register-scheme-as-privileged.injectable";
import serveExtensionFileInjectable from "./serve-extension-file.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(handleExtensionSchemeInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(registerExtensionSchemeAsPrivilegedInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(serveExtensionFileInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
