/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import NodeMenuInjectable from "./node-menu.injectable";
import podAttachMenuInjectable from "./pod-attach-menu.injectable";
import PodLogsMenuInjectable from "./pod-logs-menu.injectable";
import PodShellMenuInjectable from "./pod-shell-menu.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(NodeMenuInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(PodLogsMenuInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(PodShellMenuInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(podAttachMenuInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
