/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import isPathInjectable from "./is-path.injectable";
import uniqueHotbarNameInjectable from "./unique-hotbar-name.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(isPathInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(uniqueHotbarNameInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
