/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import httpRouteStoreInjectable from "./http-route-store.injectable";
import httpRoutesRouteComponentInjectable from "./http-routes-route-component.injectable";
import httpRoutesSidebarItemInjectable from "./http-routes-sidebar-item.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(httpRouteStoreInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(httpRoutesRouteComponentInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(httpRoutesSidebarItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
