/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import addingOfCustomHelmRepositoryDialogIsVisibleInjectable from "./adding-of-custom-helm-repository-dialog-is-visible.injectable";
import hideDialogForAddingCustomHelmRepositoryInjectable from "./hide-dialog-for-adding-custom-helm-repository.injectable";
import showDialogForAddingCustomHelmRepositoryInjectable from "./show-dialog-for-adding-custom-helm-repository.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(addingOfCustomHelmRepositoryDialogIsVisibleInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(hideDialogForAddingCustomHelmRepositoryInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(showDialogForAddingCustomHelmRepositoryInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
