/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import standaloneTerminalSessionStoreInjectable from "./session-store.injectable";
import standaloneTerminalTabsStorageInjectable from "./tabs-storage.injectable";
import standaloneTerminalTabsStoreInjectable from "./tabs-store.injectable";
import terminalRouteComponentInjectable from "./terminal-route-component.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(standaloneTerminalSessionStoreInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(standaloneTerminalTabsStorageInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(standaloneTerminalTabsStoreInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(terminalRouteComponentInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
