/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import defaultWelcomeRouteInjectable from "./default-welcome-route.injectable";
import navigateToWelcomeInjectable from "./navigate-to-welcome.injectable";
import welcomeRouteInjectable from "./welcome-route.injectable";
import welcomeRouteConfigInjectable from "./welcome-route-config.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(defaultWelcomeRouteInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(navigateToWelcomeInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(welcomeRouteConfigInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(welcomeRouteInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
