/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import reactiveTrayMenuItemsInjectable from "./reactive-tray-menu-items.injectable";
import startReactiveTrayMenuItemsInjectable from "./start-reactive-tray-menu-items.injectable";
import stopReactiveTrayMenuItemsInjectable from "./stop-reactive-tray-menu-items.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(reactiveTrayMenuItemsInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(startReactiveTrayMenuItemsInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(stopReactiveTrayMenuItemsInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
