/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import catalogSyncBroadcasterInjectable from "./broadcaster.injectable";
import catalogSyncToRendererInjectable from "./catalog-sync-to-renderer.injectable";
import pushCatalogToRendererInjectable from "./push-catalog-to-renderer.injectable";
import startCatalogSyncInjectable from "./start-catalog-sync.injectable";
import stopCatalogSyncInjectable from "./stop-catalog-sync.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(catalogSyncBroadcasterInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(catalogSyncToRendererInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(pushCatalogToRendererInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(startCatalogSyncInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(stopCatalogSyncInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
