/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import catalogCatalogEntityInjectable from "./catalog-catalog-entity.injectable";
import welcomeCatalogEntityInjectable from "./welcome-catalog-entity.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(catalogCatalogEntityInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(welcomeCatalogEntityInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
