/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import createHandlerForRouteInjectable from "./create-handler-for-route.injectable";
import parseRequestInjectable from "./parse-request.injectable";
import routerInjectable from "./router.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(createHandlerForRouteInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(parseRequestInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(routerInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
