/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import { separator1, separator2, separator3 } from "./separators.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(separator1);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(separator2);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(separator3);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
