/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import allowCommunicationToIframeInjectable from "./allow-communication-to-iframe.injectable";
import ipcRendererInjectable from "./ipc/ipc-renderer.injectable";
import enlistMessageChannelListenerInjectable from "./listening-of-messages/enlist-message-channel-listener.injectable";
import enlistRequestChannelListenerInjectable from "./listening-of-requests/enlist-request-channel-listener.injectable";
import invokeIpcInjectable from "./requesting-of-requests/invoke-ipc.injectable";
import requestFromChannelInjectable from "./requesting-of-requests/request-from-channel.injectable";
import messageToChannelInjectable from "./sending-of-messages/message-to-channel.injectable";
import sendToIpcInjectable from "./sending-of-messages/send-to-ipc.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(allowCommunicationToIframeInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(enlistMessageChannelListenerInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(enlistRequestChannelListenerInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(invokeIpcInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(ipcRendererInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(messageToChannelInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(requestFromChannelInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(sendToIpcInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
