/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import navigateToValidatingAdmissionPoliciesInjectable from "./navigate-to-validating-admission-policies.injectable";
import validatingAdmissionPoliciesRouteInjectable from "./validating-admission-policies-route.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(navigateToValidatingAdmissionPoliciesInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(validatingAdmissionPoliciesRouteInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
