/**
 * Copyright (c) Freelens Authors. All rights reserved.
 * Copyright (c) OpenLens Authors. All rights reserved.
 * Licensed under MIT License. See LICENSE in root directory for more information.
 */

import { getInjectable } from "@ogre-tools/injectable";
import { computed } from "mobx";

export interface MarketplaceExtension {
  id: string;
  name: string;
  description: string;
  version: string;
  author?: string;
  downloads?: number;
}

// Mock marketplace data - in the future, this could fetch from an API
const mockMarketplaceExtensions: MarketplaceExtension[] = [
  {
    id: "marketplace-ext-1",
    name: "@freelensapp/core",
    description: "Freelens Core",
    version: "1.7.0",
    author: "freelens",
    downloads: 0,
  },
  {
    id: "marketplace-ext-2",
    name: "@freelensapp/extensions",
    description: "Freelens - Free IDE for Kubernetes: extensions",
    version: "1.7.0",
    author: "freelens",
    downloads: 0,
  },
  {
    id: "marketplace-ext-3",
    name: "@freelensapp/freelens-node-pod-menu",
    description: "Node and pod menus for FreeLens (deprecated)",
    version: "1.1.0",
    author: "freelens",
    downloads: 0,
  },
  {
    id: "marketplace-ext-4",
    name: "@freelensapp/resource-templates",
    description: "",
    version: "1.7.0",
    author: "freelens",
    downloads: 0,
  },
  {
    id: "marketplace-ext-5",
    name: "@freelensapp/jest",
    description: "Jest configuration and scripts for Freelens packages.",
    version: "1.7.0",
    author: "freelens",
    downloads: 0,
  },
  {
    id: "marketplace-ext-6",
    name: "@freelensapp/ensure-binaries",
    description: "CLI for downloading configured versions of the bundled versions of CLIs",
    version: "1.7.0",
    author: "freelens",
    downloads: 0,
  },
  {
    id: "marketplace-ext-7",
    name: "@freelensapp/typescript",
    description: "Typescript configuration for Freelens packages.",
    version: "1.7.0",
    author: "freelens",
    downloads: 0,
  },
  {
    id: "marketplace-ext-8",
    name: "@freelensapp/legacy-extension-example",
    description: "An example bundled Freelens extensions using the v1 API",
    version: "1.2.0",
    author: "freelens",
    downloads: 0,
  },
  {
    id: "marketplace-ext-9",
    name: "@freelensapp/react-testing-library-discovery",
    description: "A way to discover HTML-elements using react-testing-library",
    version: "1.7.0",
    author: "freelens",
    downloads: 0,
  },
  {
    id: "marketplace-ext-10",
    name: "@freelensapp/eslint-config",
    description: "Freelens eslint and prettier configurations",
    version: "1.2.0",
    author: "freelens",
    downloads: 0,
  },
  {
    id: "marketplace-ext-11",
    name: "@freelensapp/generate-tray-icons",
    description: "CLI generating tray icons for building a lens-like application",
    version: "1.7.0",
    author: "freelens",
    downloads: 0,
  },
  {
    id: "marketplace-ext-12",
    name: "@freelensapp/node-fetch",
    description: "Node fetch for Freelens",
    version: "1.7.0",
    author: "freelens",
    downloads: 0,
  },
  {
    id: "marketplace-ext-13",
    name: "@freelensapp/webpack",
    description: "Webpack configurations and scripts for Lens packages.",
    version: "1.7.0",
    author: "freelens",
    downloads: 0,
  },
  {
    id: "marketplace-ext-14",
    name: "@freelensapp/kube-api-specifics",
    description: "Kube api",
    version: "1.7.0",
    author: "freelens",
    downloads: 0,
  },
  {
    id: "marketplace-ext-15",
    name: "@freelensapp/json-api",
    description: "JSON api client",
    version: "1.7.0",
    author: "freelens",
    downloads: 0,
  },
  {
    id: "marketplace-ext-16",
    name: "@freelensapp/kube-api",
    description: "Kube api",
    version: "1.7.0",
    author: "freelens",
    downloads: 0,
  },
  {
    id: "marketplace-ext-17",
    name: "@freelensapp/cluster-settings",
    description: "Injection token exporter for cluster settings configuration",
    version: "1.7.0",
    author: "freelens",
    downloads: 0,
  },
  {
    id: "marketplace-ext-18",
    name: "@freelensapp/list-layout",
    description: "Injection tokens for list layout",
    version: "1.7.0",
    author: "freelens",
    downloads: 0,
  },
  {
    id: "marketplace-ext-19",
    name: "@freelensapp/kubectl-versions",
    description: "Package of kubectl versions at build time",
    version: "1.7.0",
    author: "freelens",
    downloads: 0,
  },
  {
    id: "marketplace-ext-20",
    name: "@freelensapp/cluster-sidebar",
    description: "Injection tokens for adding new sidebar items within the Cluster View",
    version: "1.7.0",
    author: "freelens",
    downloads: 0,
  },
  {
    id: "marketplace-ext-21",
    name: "@freelensapp/legacy-global-di",
    description: "Injection tokens for implementing metrics for Freelens",
    version: "1.7.0",
    author: "freelens",
    downloads: 0,
  },
  {
    id: "marketplace-ext-22",
    name: "@freelensapp/keyboard-shortcuts",
    description: "Keyboard shortcuts for Freelens",
    version: "1.7.0",
    author: "freelens",
    downloads: 0,
  },
  {
    id: "marketplace-ext-23",
    name: "@freelensapp/logger",
    description: "Highly extendable logger in the Freelens.",
    version: "1.7.0",
    author: "freelens",
    downloads: 0,
  },
  {
    id: "marketplace-ext-24",
    name: "@freelensapp/kube-object",
    description: "Injection tokens for list layout",
    version: "1.7.0",
    author: "freelens",
    downloads: 0,
  },
  {
    id: "marketplace-ext-25",
    name: "@freelensapp/metrics",
    description: "Injection tokens for implementing metrics for Freelens",
    version: "1.7.0",
    author: "freelens",
    downloads: 0,
  },
  {
    id: "marketplace-ext-26",
    name: "@freelensapp/random",
    description: "Highly extendable random in the Freelens.",
    version: "1.7.0",
    author: "freelens",
    downloads: 0,
  },
  {
    id: "marketplace-ext-27",
    name: "@freelensapp/application",
    description: "Package for creating Freelens applications",
    version: "1.7.0",
    author: "freelens",
    downloads: 0,
  },
  {
    id: "marketplace-ext-28",
    name: "@freelensapp/routing",
    description: "Highly extendable routing in the Freelens.",
    version: "1.7.0",
    author: "freelens",
    downloads: 0,
  },
  {
    id: "marketplace-ext-29",
    name: "@freelensapp/feature-core",
    description: "Code that is common to all Features and those registering them.",
    version: "1.7.0",
    author: "freelens",
    downloads: 0,
  },
  {
    id: "marketplace-ext-30",
    name: "@freelensapp/messaging-fake-bridge",
    description: "Fake implementation to bridge multiple dependency injection containers.",
    version: "1.7.0",
    author: "freelens",
    downloads: 0,
  },
  {
    id: "marketplace-ext-31",
    name: "@freelensapp/messaging",
    description: "An abstraction for messaging between Lens environments",
    version: "1.7.0",
    author: "freelens",
    downloads: 0,
  },
  {
    id: "marketplace-ext-32",
    name: "@freelensapp/react-application",
    description: "Package for React Application",
    version: "1.7.0",
    author: "freelens",
    downloads: 0,
  },
  {
    id: "marketplace-ext-33",
    name: "@freelensapp/messaging-for-main",
    description: "Implementations for 'messaging' in Electron main",
    version: "1.7.0",
    author: "freelens",
    downloads: 0,
  },
  {
    id: "marketplace-ext-34",
    name: "@freelensapp/prometheus",
    description: "Prometheus support for Freelens",
    version: "1.7.0",
    author: "freelens",
    downloads: 0,
  },
  {
    id: "marketplace-ext-35",
    name: "@freelensapp/messaging-for-renderer",
    description: "Implementations for 'messaging' in Electron renderer",
    version: "1.7.0",
    author: "freelens",
    downloads: 0,
  },
  {
    id: "marketplace-ext-36",
    name: "@freelensapp/legacy-extensions",
    description: "Package for Lens extensions using the v1 API",
    version: "1.7.0",
    author: "freelens",
    downloads: 0,
  },
  {
    id: "marketplace-ext-37",
    name: "@freelensapp/application-for-electron-main",
    description: "Electron's main specifics for creating Freelens applications",
    version: "1.7.0",
    author: "freelens",
    downloads: 0,
  },
  {
    id: "marketplace-ext-38",
    name: "@freelensapp/animate",
    description: "Highly extendable animate in the Freelens.",
    version: "1.7.0",
    author: "freelens",
    downloads: 0,
  },
  {
    id: "marketplace-ext-39",
    name: "@freelensapp/button",
    description: "Highly extendable button in the Freelens.",
    version: "1.7.0",
    author: "freelens",
    downloads: 0,
  },
  {
    id: "marketplace-ext-40",
    name: "@freelensapp/error-boundary",
    description: "Highly extendable error-boundary in the Freelens.",
    version: "1.7.0",
    author: "freelens",
    downloads: 0,
  },
  {
    id: "marketplace-ext-41",
    name: "@freelensapp/notifications",
    description: "Highly extendable notifications in the Freelens.",
    version: "1.7.0",
    author: "freelens",
    downloads: 0,
  },
  {
    id: "marketplace-ext-42",
    name: "@freelensapp/spinner",
    description: "Highly extendable spinner in the Freelens.",
    version: "1.7.0",
    author: "freelens",
    downloads: 0,
  },
  {
    id: "marketplace-ext-43",
    name: "@freelensapp/resizing-anchor",
    description: "Highly extendable resizing-anchor in the Freelens.",
    version: "1.7.0",
    author: "freelens",
    downloads: 0,
  },
  {
    id: "marketplace-ext-44",
    name: "@freelensapp/tooltip",
    description: "Highly extendable tooltip in the Freelens.",
    version: "1.7.0",
    author: "freelens",
    downloads: 0,
  },
  {
    id: "marketplace-ext-45",
    name: "@freelensapp/event-emitter",
    description: "Event emitter",
    version: "1.7.0",
    author: "freelens",
    downloads: 0,
  },
  {
    id: "marketplace-ext-46",
    name: "@freelensapp/icon",
    description: "Highly extendable icon in the Freelens.",
    version: "1.7.0",
    author: "freelens",
    downloads: 0,
  },
  {
    id: "marketplace-ext-47",
    name: "@freelensapp/run-many",
    description: "A package containing runMany and runManySync",
    version: "1.7.0",
    author: "freelens",
    downloads: 0,
  },
  {
    id: "marketplace-ext-48",
    name: "@freelensapp/startable-stoppable",
    description: "TBD",
    version: "1.7.0",
    author: "freelens",
    downloads: 0,
  },
  {
    id: "marketplace-ext-49",
    name: "@freelensapp/test-utils",
    description: "A collection of utilities for testing",
    version: "1.7.0",
    author: "freelens",
    downloads: 0,
  },
  {
    id: "marketplace-ext-50",
    name: "@freelensapp/utilities",
    description: "A collection of useful types",
    version: "1.7.0",
    author: "freelens",
    downloads: 0,
  },
  {
    id: "marketplace-ext-51",
    name: "@freelensapp/computed-channel",
    description: "MobX-like computed between channels",
    version: "1.7.0",
    author: "freelens",
    downloads: 0,
  },
  {
    id: "marketplace-ext-52",
    name: "@freelensapp/kubernetes-client-node",
    description: "Kubernetes client for Freelens",
    version: "1.7.0",
    author: "freelens",
    downloads: 0,
  },
  {
    id: "marketplace-ext-53",
    name: "@freelensapp/extension-example",
    description: "Example of a Freelens extension (renamed to @freelensapp/example-extension)",
    version: "1.2.1",
    author: "freelens",
    downloads: 0,
  },
  {
    id: "marketplace-ext-54",
    name: "@freelensapp/openid-client",
    description: "Open ID for Freelens",
    version: "1.7.0",
    author: "freelens",
    downloads: 0,
  },
  {
    id: "marketplace-ext-55",
    name: "@freelensapp/extension-fluxcd",
    description: "Freelens extension for FluxCD",
    version: "3.2.0",
    author: "freelens",
    downloads: 0,
  },
  {
    id: "marketplace-ext-56",
    name: "@freelensapp/example-extension",
    description: "Example of a Freelens extension",
    version: "1.6.2",
    author: "freelens",
    downloads: 0,
  },
  {
    id: "marketplace-ext-57",
    name: "@freelensapp/ai-extension",
    description: "AI capabilities for Freelens",
    version: "0.4.1",
    author: "freelens",
    downloads: 0,
  },
  {
    id: "marketplace-ext-58",
    name: "@freelensapp/fluxcd-extension",
    description: "Freelens extension for FluxCD",
    version: "5.2.1",
    author: "freelens",
    downloads: 0,
  },
  {
    id: "marketplace-ext-59",
    name: "@freelensapp/generate-license",
    description: "CLI for generating license files",
    version: "1.7.0",
    author: "freelens",
    downloads: 0,
  },
];

const marketplaceExtensionsInjectable = getInjectable({
  id: "marketplace-extensions",

  instantiate: () => {
    // Returns a computed observable that can be reactive in the future
    return computed(() => mockMarketplaceExtensions);
  },
});

export default marketplaceExtensionsInjectable;
