/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import apiBaseHostHeaderInjectable from "./api-base-host-header.injectable";
import apiBaseServerAddressInjectable from "./api-base-server-address.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(apiBaseHostHeaderInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(apiBaseServerAddressInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
