/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import confirmInjectable from "./confirm.injectable";
import confirmDialogClusterFrameChildComponentInjectable from "./confirm-dialog-cluster-frame-child-component.injectable";
import confirmDialogRootFrameChildComponentInjectable from "./confirm-dialog-root-frame-child-component.injectable";
import openConfirmDialogInjectable from "./open.injectable";
import confirmDialogStateInjectable from "./state.injectable";
import withConfirmationInjectable from "./with-confirm.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(confirmDialogClusterFrameChildComponentInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(confirmDialogRootFrameChildComponentInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(confirmDialogStateInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(confirmInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(openConfirmDialogInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(withConfirmationInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
