/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file imports and registers all injectables from subdirectories.
 * This replaces the webpack-based auto-registration system.
 */

import contextMenuTopBarItemInjectable from "./context-menu-top-bar-item.injectable";
import { registerInjectables as registerOpenAppContextMenuInjectables } from "./open-app-context-menu/register-injectables";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(contextMenuTopBarItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerOpenAppContextMenuInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
