/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file imports and registers all injectables from subdirectories.
 * This replaces the webpack-based auto-registration system.
 */

import orderByUrlParamInjectable from "./order-by-url-param.injectable";
import sortByUrlParamInjectable from "./sort-by-url-param.injectable";
import { registerInjectables as registerTableModelInjectables } from "./table-model/register-injectables";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(orderByUrlParamInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(sortByUrlParamInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerTableModelInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
