/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file imports and registers all injectables from subdirectories.
 * This replaces the webpack-based auto-registration system.
 */

import { registerInjectables as registerDialogInjectables } from "./dialog/register-injectables";
import roleBindingsRouteComponentInjectable from "./role-bindings-route-component.injectable";
import roleBindingsSidebarItemInjectable from "./role-bindings-sidebar-item.injectable";
import roleBindingStoreInjectable from "./store.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(roleBindingStoreInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(roleBindingsRouteComponentInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(roleBindingsSidebarItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerDialogInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
