/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import autoRegistrationEmitterInjectable from "./auto-registration-emitter.injectable";
import createCustomResourceStoreInjectable from "./create-custom-resource-store.injectable";
import apiManagerInjectable from "./manager.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(apiManagerInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(autoRegistrationEmitterInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(createCustomResourceStoreInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
