/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file imports and registers all injectables from subdirectories.
 * This replaces the webpack-based auto-registration system.
 */

import { registerInjectables as registerBindProtocolAddRouteHandlersInjectables } from "./bind-protocol-add-route-handlers/register-injectables";
import { registerInjectables as registerLensProtocolRouterRendererInjectables } from "./lens-protocol-router-renderer/register-injectables";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    registerBindProtocolAddRouteHandlersInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerLensProtocolRouterRendererInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
