/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file imports and registers all injectables from subdirectories.
 * This replaces the webpack-based auto-registration system.
 */

import releaseDetailsClusterFrameChildComponentInjectable from "./release-details-cluster-frame-child-component.injectable";
import { registerInjectables as registerReleaseDetailsModelInjectables } from "./release-details-model/register-injectables";
import targetHelmReleaseInjectable from "./target-helm-release.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(releaseDetailsClusterFrameChildComponentInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(targetHelmReleaseInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerReleaseDetailsModelInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
