/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file imports and registers all injectables from subdirectories.
 * This replaces the webpack-based auto-registration system.
 */

import helpMenuItemInjectable from "./help-menu-item.injectable";
import { registerInjectables as registerNavigateToWelcomeInjectables } from "./navigate-to-welcome/register-injectables";
import { registerInjectables as registerOpenDocumentationInjectables } from "./open-documentation/register-injectables";
import { registerInjectables as registerOpenLicensesInjectables } from "./open-licenses/register-injectables";
import { registerInjectables as registerOpenSupportInjectables } from "./open-support/register-injectables";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(helpMenuItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerNavigateToWelcomeInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerOpenDocumentationInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerOpenLicensesInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerOpenSupportInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
