/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file imports and registers all injectables from subdirectories.
 * This replaces the webpack-based auto-registration system.
 */

import extensionSidebarItemRegistratorInjectable from "./extension-sidebar-item-registrator.injectable";
import { registerInjectables as registerSidebarStorageInjectables } from "./sidebar-storage/register-injectables";
import { registerInjectables as registerTopBarInjectables } from "./top-bar/register-injectables";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(extensionSidebarItemRegistratorInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerSidebarStorageInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerTopBarInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
