/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import clearCreateResourceTabDataInjectable from "./clear-create-resource-tab-data.injectable";
import createResourceTabInjectable from "./create-resource-tab.injectable";
import createResourceTemplatesInjectable from "./create-resource-templates.injectable";
import lensCreateResourceTemplatesInjectable from "./lens-templates.injectable";
import createResourceTabStoreInjectable from "./store.injectable";
import userCreateResourceTemplatesInjectable from "./user-templates.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(clearCreateResourceTabDataInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(createResourceTabInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(createResourceTabStoreInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(createResourceTemplatesInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(lensCreateResourceTemplatesInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(userCreateResourceTemplatesInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
