/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import grpcRoutesRouteInjectable from "./grpc-routes-route.injectable";
import navigateToGRPCRoutesInjectable from "./navigate-to-grpc-routes.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(grpcRoutesRouteInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(navigateToGRPCRoutesInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
