/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import { buildVersionInitializationInjectable, buildVersionStateInjectable } from "./init.injectable";
import buildVersionChannelListenerInjectable from "./request-channel.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(buildVersionChannelListenerInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(buildVersionInitializationInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(buildVersionStateInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
