/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import navigateToReferenceGrantsInjectable from "./navigate-to-reference-grants.injectable";
import referenceGrantsRouteInjectable from "./reference-grants-route.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(navigateToReferenceGrantsInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(referenceGrantsRouteInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
