# Trailing spaces
MD009: false
# Multiple consecutive blank lines
MD012: false
# Line length
MD013: false
# Headings should be surrounded by blank lines
MD022: false
# Ordered list item prefix
MD029: false
# Fenced code blocks should be surrounded by blank lines
MD031: false
# Lists should be surrounded by blank lines
MD032: false
# Inline HTML
MD033:
  allowed_elements:
    - br
    - img
    - picture
    - source
# Emphasis used instead of a header
MD036: false
# Table column style
MD060: false
