packages:
  - freelens
  - packages/**

nodeGyp: ../../../../node-gyp/bin/node-gyp.js

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - core-js-pure
  - electron
  - electron-winstaller
  - esbuild
  - node-pty
  - playwright
  - sharp

overrides:
  http-proxy: npm:http-proxy-node16@^1.0.0
  http-proxy-middleware: ^3.0.0
  '@types/http-proxy': '-'

patchedDependencies:
  circular-dependency-plugin: patches/circular-dependency-plugin.patch
  monaco-editor: patches/monaco-editor.patch
  '@async-fn/jest': patches/@async-fn__jest.patch

publicHoistPattern:
  - node-gyp

shellEmulator: true
