packages:
  - freelens
  - packages/**

onlyBuiltDependencies:
  - '@parcel/watcher'
  - core-js-pure
  - electron
  - electron-winstaller
  - esbuild
  - node-pty
  - playwright
  - sharp
  - win-ca

overrides:
  brace-expansion: npm:brace-expansion@^4.0.1
  http-proxy: npm:http-proxy-node16@^1.0.0
  http-proxy-middleware: ^3.0.0
  '@types/http-proxy': '-'

patchedDependencies:
  circular-dependency-plugin: patches/circular-dependency-plugin.patch
  monaco-editor: patches/monaco-editor.patch

publicHoistPattern:
  - node-gyp

nodeGyp: ../../../../node-gyp/bin/node-gyp.js

shellEmulator: true
