packages:
  - freelens
  - packages/**

publicHoistPattern:
  - '@types/webpack-env'
  - '*css-loader*'
  - '*ts-loader*'
  - '*sass-loader*'
  - eslint
  - webpack

onlyBuiltDependencies:
  - '@parcel/watcher'
  - core-js-pure
  - electron
  - electron-winstaller
  - esbuild
  - node-pty
  - playwright
  - sharp
  - win-ca

patchedDependencies:
  monaco-editor: patches/monaco-editor.patch
