/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file imports and registers all injectables from subdirectories.
 * This replaces the webpack-based auto-registration system.
 */

import { registerInjectables as registerAddDialogInjectables } from "./add-dialog/register-injectables";
import resourceQuotasRouteComponentInjectable from "./resource-quotas-route-component.injectable";
import resourceQuotasSidebarItemInjectable from "./resource-quotas-sidebar-item.injectable";
import resourceQuotaStoreInjectable from "./store.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(resourceQuotaStoreInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(resourceQuotasRouteComponentInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(resourceQuotasSidebarItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerAddDialogInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
