/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import portForwardsRouteComponentInjectable from "./port-forwards-route-component.injectable";
import portForwardsRouteParametersInjectable from "./port-forwards-route-parameters.injectable";
import portForwardsSidebarItemInjectable from "./port-forwards-sidebar-item.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(portForwardsRouteComponentInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(portForwardsRouteParametersInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(portForwardsSidebarItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
