/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file imports and registers all injectables from subdirectories.
 * This replaces the webpack-based auto-registration system.
 */

import persistentSearchStoreInjectable from "./persistent-search-store.injectable";
import searchUrlPageParamInjectable from "./search-url-page-param.injectable";
import { registerInjectables as registerValidatorsInjectables } from "./validators/register-injectables";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(persistentSearchStoreInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(searchUrlPageParamInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerValidatorsInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
