/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import directoryForExtensionDataInjectable from "./directory-for-extension-data.injectable";
import ensureHashedDirectoryForExtensionInjectable from "./ensure-hashed-directory-for-extension.injectable";
import fileSystemProvisionerStoreInjectable from "./file-system-provisioner-store.injectable";
import getHashInjectable from "./get-hash.injectable";
import getPathToLegacyPackageJson from "./get-path-to-legacy-package-json.injectable";
import { registeredExtensionsInjectable } from "./registered-extensions.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(directoryForExtensionDataInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(ensureHashedDirectoryForExtensionInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(fileSystemProvisionerStoreInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(getHashInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(getPathToLegacyPackageJson);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(registeredExtensionsInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
