/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import {
  logDebugInjectable,
  logErrorInjectable,
  loggerInjectable,
  logInfoInjectable,
  logSillyInjectable,
  logWarningInjectable,
} from "./logger.injectable";
import { prefixedLoggerInjectable } from "./prefixed-logger.injectable";
import { winstonLoggerInjectable } from "./winston-logger.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(logDebugInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(logErrorInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(logInfoInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(logSillyInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(logWarningInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(loggerInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(prefixedLoggerInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(winstonLoggerInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
