/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import mutatingWebhookConfigurationStoreInjectable from "./mutating-webhook-configuration-store.injectable";
import mutatingWebhookConfigurationsRouteComponentInjectable from "./mutating-webhook-configurations-route-component.injectable";
import mutatingWebhookConfigurationsSidebarItemInjectable from "./mutating-webhook-configurations-sidebar-items.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(mutatingWebhookConfigurationStoreInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(mutatingWebhookConfigurationsRouteComponentInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(mutatingWebhookConfigurationsSidebarItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
