/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import emitSystemThemeTypeUpdateInjectable from "./emit-update.injectable";
import initialSystemThemeTypeHandler from "./handle-initial.injectable";
import setupSystemThemeTypeUpdaterEmitterInjectable from "./setup-update-emitter.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(emitSystemThemeTypeUpdateInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(initialSystemThemeTypeHandler);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(setupSystemThemeTypeUpdaterEmitterInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
