/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file imports and registers all injectables from subdirectories.
 * This replaces the webpack-based auto-registration system.
 */

import { registerInjectables as registerLensWindowInjectables } from "./lens-window/register-injectables";
import { registerInjectables as registerRunnablesInjectables } from "./runnables/register-injectables";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    registerLensWindowInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerRunnablesInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
