/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import runtimeClassesRouteComponentInjectable from "./runtime-classes-route-component.injectable";
import runtimeClassesSidebarItemInjectable from "./runtime-classes-sidebar-item.injectable";
import runtimeClassStoreInjectable from "./store.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(runtimeClassStoreInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(runtimeClassesRouteComponentInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(runtimeClassesSidebarItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
