/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import gatewayClassStoreInjectable from "./gateway-class-store.injectable";
import gatewayClassesRouteComponentInjectable from "./gateway-classes-route-component.injectable";
import gatewayClassesSidebarItemInjectable from "./gateway-classes-sidebar-item.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(gatewayClassStoreInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(gatewayClassesRouteComponentInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(gatewayClassesSidebarItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
