/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file imports and registers all injectables from subdirectories.
 * This replaces the webpack-based auto-registration system.
 */

import cleanUpShellSessionsInjectable from "./clean-up-shell-sessions.injectable";
import emitCloseToEventBusInjectable from "./emit-close-to-event-bus.injectable";
import emitServiceStartToEventBusInjectable from "./emit-service-start-to-event-bus.injectable";
import { registerInjectables as registerFlagRendererInjectables } from "./flag-renderer/register-injectables";
import initializeExtensionsInjectable from "./initialize-extensions.injectable";
import { registerInjectables as registerKubeConfigSyncInjectables } from "./kube-config-sync/register-injectables";
import { registerInjectables as registerRootFrameHasRenderedInjectables } from "./root-frame-has-rendered/register-injectables";
import setupHardwareAccelerationInjectable from "./setup-hardware-acceleration.injectable";
import setupHostnamesInjectable from "./setup-hostnames.injectable";
import setupImmerInjectable from "./setup-immer.injectable";
import setupLensProxyInjectable from "./setup-lens-proxy.injectable";
import setupLensProxyCertificateInjectable from "./setup-lens-proxy-certificate.injectable";
import setupMobxInjectable from "./setup-mobx.injectable";
import setupProxyEnvInjectable from "./setup-proxy-env.injectable";
import setupSyncingOfGeneralCatalogEntitiesInjectable from "./setup-syncing-of-general-catalog-entities.injectable";
import showInitialWindowInjectable from "./show-initial-window.injectable";
import showLoadingInjectable from "./show-loading.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(cleanUpShellSessionsInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(emitCloseToEventBusInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(emitServiceStartToEventBusInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(initializeExtensionsInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(setupHardwareAccelerationInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(setupHostnamesInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(setupImmerInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(setupLensProxyCertificateInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(setupLensProxyInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(setupMobxInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(setupProxyEnvInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(setupSyncingOfGeneralCatalogEntitiesInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(showInitialWindowInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(showLoadingInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerFlagRendererInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerKubeConfigSyncInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerRootFrameHasRenderedInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
