/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import { execInjectable } from "./scripts/exec.injectable";
import { logSuccessInjectable } from "./scripts/log-success.injectable";
import { logWarningInjectable } from "./scripts/log-warning.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(execInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(logSuccessInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(logWarningInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
