/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import currentPathInjectable from "./current-path.injectable";
import currentRouteInjectable from "./current-route.injectable";
import currentRouteComponentInjectable from "./current-route-component.injectable";
import currentlyInClusterFrameInjectable from "./currently-in-cluster-frame.injectable";
import extensionPageParametersInjectable from "./extension-page-parameters.injectable";
import extensionRouteRegistratorInjectable from "./extension-route-registrator.injectable";
import getExtensionPageParametersInjectable from "./get-extension-page-parameters.injectable";
import matchingRouteInjectable from "./matching-route.injectable";
import navigateToRouteInjectable from "./navigate-to-route.injectable";
import navigateToUrlInjectable from "./navigate-to-url.injectable";
import queryParametersInjectable from "./query-parameters.injectable";
import routeIsActiveInjectable from "./route-is-active.injectable";
import routePathParametersInjectable from "./route-path-parameters.injectable";
import routesInjectable from "./routes.injectable";
import siblingTabsInjectable from "./sibling-tabs.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(currentPathInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(currentRouteComponentInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(currentRouteInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(currentlyInClusterFrameInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(extensionPageParametersInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(extensionRouteRegistratorInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(getExtensionPageParametersInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(matchingRouteInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(navigateToRouteInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(navigateToUrlInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(queryParametersInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(routeIsActiveInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(routePathParametersInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(routesInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(siblingTabsInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
