/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import aboutAppTrayItemInjectable from "./about-app-tray-item.injectable";
import openAppTrayItemInjectable from "./open-app-tray-item.injectable";
import quitAppSeparatorTrayItemInjectable from "./quit-app-separator-tray-item.injectable";
import quitAppTrayItemInjectable from "./quit-app-tray-item.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(aboutAppTrayItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(openAppTrayItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(quitAppSeparatorTrayItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(quitAppTrayItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
