/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file imports and registers all injectables from subdirectories.
 * This replaces the webpack-based auto-registration system.
 */

import deleteHelmReleaseInjectable from "./delete-helm-release.injectable";
import { registerInjectables as registerExecHelmInjectables } from "./exec-helm/register-injectables";
import { registerInjectables as registerGetHelmEnvInjectables } from "./get-helm-env/register-injectables";
import getHelmReleaseHistoryInjectable from "./get-helm-release-history.injectable";
import getHelmReleaseValuesInjectable from "./get-helm-release-values.injectable";
import helmBinaryPathInjectable from "./helm-binary-path.injectable";
import helmChartManagerInjectable from "./helm-chart-manager.injectable";
import helmChartManagerCacheInjectable from "./helm-chart-manager-cache.injectable";
import { registerInjectables as registerHelmServiceInjectables } from "./helm-service/register-injectables";
import installHelmChartInjectable from "./install-helm-chart.injectable";
import listHelmReleasesInjectable from "./list-helm-releases.injectable";
import { registerInjectables as registerRepositoriesInjectables } from "./repositories/register-injectables";
import rollbackHelmReleaseInjectable from "./rollback-helm-release.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(deleteHelmReleaseInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(getHelmReleaseHistoryInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(getHelmReleaseValuesInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(helmBinaryPathInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(helmChartManagerCacheInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(helmChartManagerInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(installHelmChartInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(listHelmReleasesInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(rollbackHelmReleaseInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerExecHelmInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerGetHelmEnvInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerHelmServiceInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerRepositoriesInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
