/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file imports and registers all injectables from subdirectories.
 * This replaces the webpack-based auto-registration system.
 */

import { registerInjectables as registerBackendTlsPoliciesInjectables } from "./backend-tls-policies/register-injectables";
import gatewayApiSidebarItemInjectable from "./gateway-api-sidebar-item.injectable";
import { registerInjectables as registerGatewayClassesInjectables } from "./gateway-classes/register-injectables";
import { registerInjectables as registerGatewaysInjectables } from "./gateways/register-injectables";
import { registerInjectables as registerGrpcRoutesInjectables } from "./grpc-routes/register-injectables";
import { registerInjectables as registerHttpRoutesInjectables } from "./http-routes/register-injectables";
import { registerInjectables as registerReferenceGrantsInjectables } from "./reference-grants/register-injectables";
import { registerInjectables as registerTcpRoutesInjectables } from "./tcp-routes/register-injectables";
import { registerInjectables as registerTlsRoutesInjectables } from "./tls-routes/register-injectables";
import { registerInjectables as registerUdpRoutesInjectables } from "./udp-routes/register-injectables";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(gatewayApiSidebarItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerBackendTlsPoliciesInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerGatewayClassesInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerGatewaysInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerGrpcRoutesInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerHttpRoutesInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerReferenceGrantsInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerTcpRoutesInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerTlsRoutesInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerUdpRoutesInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
