/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file imports and registers all injectables from subdirectories.
 * This replaces the webpack-based auto-registration system.
 */

import { registerInjectables as registerAddClusterInjectables } from "./add-cluster/register-injectables";
import { registerInjectables as registerBadgeInjectables } from "./badge/register-injectables";
import { registerInjectables as registerCatalogInjectables } from "./catalog/register-injectables";
import { registerInjectables as registerClusterInjectables } from "./cluster/register-injectables";
import { registerInjectables as registerClusterManagerInjectables } from "./cluster-manager/register-injectables";
import { registerInjectables as registerClusterSettingsInjectables } from "./cluster-settings/register-injectables";
import { registerInjectables as registerCommandPaletteInjectables } from "./command-palette/register-injectables";
import { registerInjectables as registerConfigInjectables } from "./config/register-injectables";
import { registerInjectables as registerConfigHorizontalPodAutoscalersInjectables } from "./config-horizontal-pod-autoscalers/register-injectables";
import { registerInjectables as registerConfigLeasesInjectables } from "./config-leases/register-injectables";
import { registerInjectables as registerConfigLimitRangesInjectables } from "./config-limit-ranges/register-injectables";
import { registerInjectables as registerConfigMapsInjectables } from "./config-maps/register-injectables";
import { registerInjectables as registerConfigMutatingWebhookConfigurationsInjectables } from "./config-mutating-webhook-configurations/register-injectables";
import { registerInjectables as registerConfigPodDisruptionBudgetsInjectables } from "./config-pod-disruption-budgets/register-injectables";
import { registerInjectables as registerConfigPriorityClassesInjectables } from "./config-priority-classes/register-injectables";
import { registerInjectables as registerConfigResourceQuotasInjectables } from "./config-resource-quotas/register-injectables";
import { registerInjectables as registerConfigRuntimeClassesInjectables } from "./config-runtime-classes/register-injectables";
import { registerInjectables as registerConfigSecretsInjectables } from "./config-secrets/register-injectables";
import { registerInjectables as registerConfigValidatingWebhookConfigurationsInjectables } from "./config-validating-webhook-configurations/register-injectables";
import { registerInjectables as registerConfigVerticalPodAutoscalersInjectables } from "./config-vertical-pod-autoscalers/register-injectables";
import { registerInjectables as registerConfirmDialogInjectables } from "./confirm-dialog/register-injectables";
import { registerInjectables as registerCountdownInjectables } from "./countdown/register-injectables";
import { registerInjectables as registerCustomResourceDefinitionsInjectables } from "./custom-resource-definitions/register-injectables";
import { registerInjectables as registerCustomResourcesInjectables } from "./custom-resources/register-injectables";
import { registerInjectables as registerDeleteClusterDialogInjectables } from "./delete-cluster-dialog/register-injectables";
import { registerInjectables as registerDockInjectables } from "./dock/register-injectables";
import { registerInjectables as registerDrawerInjectables } from "./drawer/register-injectables";
import { registerInjectables as registerEntitySettingsInjectables } from "./entity-settings/register-injectables";
import { registerInjectables as registerEventsInjectables } from "./events/register-injectables";
import { registerInjectables as registerExtensionsInjectables } from "./extensions/register-injectables";
import { registerInjectables as registerFavoritesInjectables } from "./favorites/register-injectables";
import { registerInjectables as registerHelmInjectables } from "./helm/register-injectables";
import { registerInjectables as registerHelmChartsInjectables } from "./helm-charts/register-injectables";
import { registerInjectables as registerHelmReleasesInjectables } from "./helm-releases/register-injectables";
import { registerInjectables as registerInputInjectables } from "./input/register-injectables";
import { registerInjectables as registerItemObjectListInjectables } from "./item-object-list/register-injectables";
import { registerInjectables as registerKubeDetailParamsInjectables } from "./kube-detail-params/register-injectables";
import { registerInjectables as registerKubeObjectDetailsInjectables } from "./kube-object-details/register-injectables";
import { registerInjectables as registerKubeObjectMenuInjectables } from "./kube-object-menu/register-injectables";
import { registerInjectables as registerKubeconfigDialogInjectables } from "./kubeconfig-dialog/register-injectables";
import { registerInjectables as registerLayoutInjectables } from "./layout/register-injectables";
import { registerInjectables as registerMonacoEditorInjectables } from "./monaco-editor/register-injectables";
import { registerInjectables as registerNamespacesInjectables } from "./namespaces/register-injectables";
import { registerInjectables as registerNetworkInjectables } from "./network/register-injectables";
import { registerInjectables as registerNetworkEndpointSlicesInjectables } from "./network-endpoint-slices/register-injectables";
import { registerInjectables as registerNetworkEndpointsInjectables } from "./network-endpoints/register-injectables";
import { registerInjectables as registerNetworkGatewayApiInjectables } from "./network-gateway-api/register-injectables";
import { registerInjectables as registerNetworkIngressesInjectables } from "./network-ingresses/register-injectables";
import { registerInjectables as registerNetworkPoliciesInjectables } from "./network-policies/register-injectables";
import { registerInjectables as registerNetworkPortForwardsInjectables } from "./network-port-forwards/register-injectables";
import { registerInjectables as registerNetworkServicesInjectables } from "./network-services/register-injectables";
import { registerInjectables as registerNodePodMenuInjectables } from "./node-pod-menu/register-injectables";
import { registerInjectables as registerNodesInjectables } from "./nodes/register-injectables";
import { registerInjectables as registerPodSecurityPoliciesInjectables } from "./pod-security-policies/register-injectables";
import { registerInjectables as registerRenderDelayInjectables } from "./render-delay/register-injectables";
import { registerInjectables as registerStatusBarInjectables } from "./status-bar/register-injectables";
import { registerInjectables as registerStorageInjectables } from "./storage/register-injectables";
import { registerInjectables as registerStorageClassesInjectables } from "./storage-classes/register-injectables";
import { registerInjectables as registerStorageVolumeClaimsInjectables } from "./storage-volume-claims/register-injectables";
import { registerInjectables as registerStorageVolumesInjectables } from "./storage-volumes/register-injectables";
import { registerInjectables as registerTableInjectables } from "./table/register-injectables";
import { registerInjectables as registerUserManagementInjectables } from "./user-management/register-injectables";
import { registerInjectables as registerWelcomeInjectables } from "./welcome/register-injectables";
import { registerInjectables as registerWorkloadsInjectables } from "./workloads/register-injectables";
import { registerInjectables as registerWorkloadsCronjobsInjectables } from "./workloads-cronjobs/register-injectables";
import { registerInjectables as registerWorkloadsDaemonsetsInjectables } from "./workloads-daemonsets/register-injectables";
import { registerInjectables as registerWorkloadsDeploymentsInjectables } from "./workloads-deployments/register-injectables";
import { registerInjectables as registerWorkloadsJobsInjectables } from "./workloads-jobs/register-injectables";
import { registerInjectables as registerWorkloadsOverviewInjectables } from "./workloads-overview/register-injectables";
import { registerInjectables as registerWorkloadsPodsInjectables } from "./workloads-pods/register-injectables";
import { registerInjectables as registerWorkloadsReplicasetsInjectables } from "./workloads-replicasets/register-injectables";
import { registerInjectables as registerWorkloadsReplicationControllersInjectables } from "./workloads-replication-controllers/register-injectables";
import { registerInjectables as registerWorkloadsStatefulsetsInjectables } from "./workloads-statefulsets/register-injectables";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    registerAddClusterInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerBadgeInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerCatalogInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerClusterInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerClusterManagerInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerClusterSettingsInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerCommandPaletteInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerConfigInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerConfigHorizontalPodAutoscalersInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerConfigLeasesInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerConfigLimitRangesInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerConfigMapsInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerConfigMutatingWebhookConfigurationsInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerConfigPodDisruptionBudgetsInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerConfigPriorityClassesInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerConfigResourceQuotasInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerConfigRuntimeClassesInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerConfigSecretsInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerConfigValidatingWebhookConfigurationsInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerConfigVerticalPodAutoscalersInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerConfirmDialogInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerCountdownInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerCustomResourceDefinitionsInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerCustomResourcesInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerDeleteClusterDialogInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerDockInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerDrawerInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerEntitySettingsInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerEventsInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerExtensionsInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerFavoritesInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerHelmInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerHelmChartsInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerHelmReleasesInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerInputInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerItemObjectListInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerKubeDetailParamsInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerKubeObjectDetailsInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerKubeObjectMenuInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerKubeconfigDialogInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerLayoutInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerMonacoEditorInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerNamespacesInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerNetworkInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerNetworkEndpointSlicesInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerNetworkEndpointsInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerNetworkGatewayApiInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerNetworkIngressesInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerNetworkPoliciesInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerNetworkPortForwardsInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerNetworkServicesInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerNodePodMenuInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerNodesInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerPodSecurityPoliciesInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerRenderDelayInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerStatusBarInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerStorageInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerStorageClassesInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerStorageVolumeClaimsInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerStorageVolumesInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerTableInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerUserManagementInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerWelcomeInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerWorkloadsInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerWorkloadsCronjobsInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerWorkloadsDaemonsetsInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerWorkloadsDeploymentsInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerWorkloadsJobsInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerWorkloadsOverviewInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerWorkloadsPodsInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerWorkloadsReplicasetsInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerWorkloadsReplicationControllersInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerWorkloadsStatefulsetsInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
