/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import getAllClustersInjectable from "./get-all-clusters.injectable";
import getAllClustersListenerInjectable from "./get-all-clusters-channel-listener.injectable";
import getClusterByIdInjectable from "./get-cluster-by-id.injectable";
import getClusterByIdListenerInjectable from "./get-cluster-by-id-channel-listener.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(getAllClustersInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(getAllClustersListenerInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(getClusterByIdInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(getClusterByIdListenerInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
