/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import getHorizontalPodAutoscalerMetrics from "./get-metrics.injectable";
import horizontalPodAutoscalersRouteComponentInjectable from "./route-component.injectable";
import horizontalPodAutoscalersSidebarItemInjectable from "./sidebar-item.injectable";
import horizontalPodAutoscalerStoreInjectable from "./store.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(getHorizontalPodAutoscalerMetrics);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(horizontalPodAutoscalerStoreInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(horizontalPodAutoscalersRouteComponentInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(horizontalPodAutoscalersSidebarItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
