/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file imports and registers all injectables from subdirectories.
 * This replaces the webpack-based auto-registration system.
 */

import { registerInjectables as registerEndpointSlicesInjectables } from "./endpoint-slices/register-injectables";
import { registerInjectables as registerEndpointsInjectables } from "./endpoints/register-injectables";
import { registerInjectables as registerGatewayClassesInjectables } from "./gateway-classes/register-injectables";
import { registerInjectables as registerGatewaysInjectables } from "./gateways/register-injectables";
import { registerInjectables as registerGrpcRoutesInjectables } from "./grpc-routes/register-injectables";
import { registerInjectables as registerHttpRoutesInjectables } from "./http-routes/register-injectables";
import { registerInjectables as registerIngressClassInjectables } from "./ingress-class/register-injectables";
import { registerInjectables as registerIngressesInjectables } from "./ingresses/register-injectables";
import { registerInjectables as registerNetworkPoliciesInjectables } from "./network-policies/register-injectables";
import { registerInjectables as registerPortForwardsInjectables } from "./port-forwards/register-injectables";
import { registerInjectables as registerReferenceGrantsInjectables } from "./reference-grants/register-injectables";
import { registerInjectables as registerServicesInjectables } from "./services/register-injectables";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    registerEndpointSlicesInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerEndpointsInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerGatewayClassesInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerGatewaysInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerGrpcRoutesInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerHttpRoutesInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerIngressClassInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerIngressesInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerNetworkPoliciesInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerPortForwardsInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerReferenceGrantsInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerServicesInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
