/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import requestClearClusterAsDeletingInjectable from "./request-clear-as-deleting.injectable";
import requestDeleteClusterInjectable from "./request-delete.injectable";
import requestSetClusterAsDeletingInjectable from "./request-set-as-deleting.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(requestClearClusterAsDeletingInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(requestDeleteClusterInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(requestSetClusterAsDeletingInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
