/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import endpointsRouteInjectable from "./endpoints-route.injectable";
import navigateToEndpointsInjectable from "./navigate-to-endpoints.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(endpointsRouteInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(navigateToEndpointsInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
