/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import deleteReleaseRouteInjectable from "./delete-release-route.injectable";
import getReleaseRouteHistoryInjectable from "./get-release-history-route.injectable";
import getReleaseRouteValuesInjectable from "./get-release-values-route.injectable";
import installChartRouteInjectable from "./install-chart-route.injectable";
import rollbackReleaseRouteInjectable from "./rollback-release-route.injectable";
import updateReleaseRouteInjectable from "./update-release-route.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(deleteReleaseRouteInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(getReleaseRouteHistoryInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(getReleaseRouteValuesInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(installChartRouteInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(rollbackReleaseRouteInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(updateReleaseRouteInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
