/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import createStorageInjectable from "./create-storage.injectable";
import initializeStateInjectable from "./initialize-state.injectable";
import lensLocalStorageStateInjectable from "./state.injectable";
import storageSaveDelayInjectable from "./storage-save-delay.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(createStorageInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(initializeStateInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(lensLocalStorageStateInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(storageSaveDelayInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
