/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import tlsRouteStoreInjectable from "./tls-route-store.injectable";
import tlsRoutesRouteComponentInjectable from "./tls-routes-route-component.injectable";
import tlsRoutesSidebarItemInjectable from "./tls-routes-sidebar-item.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(tlsRouteStoreInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(tlsRoutesRouteComponentInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(tlsRoutesSidebarItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
