/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import getHelmChartReadmeRouteInjectable from "./get-readme-route.injectable";
import getHelmChartRouteValuesInjectable from "./get-values-route.injectable";
import getHelmChartVersionsRouteInjectable from "./get-versions-route.injectable";
import listHelmChartsRouteInjectable from "./list-route.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(getHelmChartReadmeRouteInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(getHelmChartRouteValuesInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(getHelmChartVersionsRouteInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(listHelmChartsRouteInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
