/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file imports and registers all injectables from subdirectories.
 * This replaces the webpack-based auto-registration system.
 */

import { registerInjectables as registerGoForwardInjectables } from "./go-forward/register-injectables";
import navigationToForwardTopBarItemInjectable from "./navigation-to-forward-top-bar-item.injectable";
import topBarNextEnabledInjectable from "./next-enabled.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(navigationToForwardTopBarItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(topBarNextEnabledInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerGoForwardInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
