/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import mutatingWebhookConfigurationsRouteInjectable from "./mutating-webhook-configurations-route.injectable";
import navigateToMutatingWebhookConfigurationsInjectable from "./navigate-to-mutating-webhook-configurations.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(mutatingWebhookConfigurationsRouteInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(navigateToMutatingWebhookConfigurationsInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
