/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import validatingAdmissionPolicyBindingStoreInjectable from "./validating-admission-policy-binding-store.injectable";
import validatingAdmissionPolicyBindingsRouteComponentInjectable from "./validating-admission-policy-bindings-route-component.injectable";
import validatingAdmissionPolicyBindingsSidebarItemInjectable from "./validating-admission-policy-bindings-sidebar-items.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(validatingAdmissionPolicyBindingStoreInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(validatingAdmissionPolicyBindingsRouteComponentInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(validatingAdmissionPolicyBindingsSidebarItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
