/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import downloadBinaryViaChannelInjectable from "./download-binary-via-channel.injectable";
import downloadJsonViaChannelInjectable from "./download-json-via-channel-copy.injectable";
import fetchInjectable from "./fetch.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(downloadBinaryViaChannelInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(downloadJsonViaChannelInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(fetchInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
