/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import enlistMessageChannelListenerInjectable from "./channel-listeners/enlist-message-channel-listener.injectable";
import enlistRequestChannelListenerInjectable from "./channel-listeners/enlist-request-channel-listener.injectable";
import ipcMainInjectable from "./ipc-main/ipc-main.injectable";
import requestFromChannelInjectable from "./request-from-channel/request-from-channel.injectable";
import allowCommunicationListenerInjectable from "./send-message-to-channel/allow-communication-listener.injectable";
import frameIdsInjectable from "./send-message-to-channel/frameIds.injectable";
import getWebContentsInjectable from "./send-message-to-channel/get-web-contents.injectable";
import sendMessageToChannelInjectable from "./send-message-to-channel/send-message-to-channel.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(allowCommunicationListenerInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(enlistMessageChannelListenerInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(enlistRequestChannelListenerInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(frameIdsInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(getWebContentsInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(ipcMainInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(requestFromChannelInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(sendMessageToChannelInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
