/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import httpRoutesRouteInjectable from "./http-routes-route.injectable";
import navigateToHTTPRoutesInjectable from "./navigate-to-http-routes.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(httpRoutesRouteInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(navigateToHTTPRoutesInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
