/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import electronTrayInjectable from "./electron-tray.injectable";
import startTrayInjectable from "./start-tray.injectable";
import stopTrayInjectable from "./stop-tray.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(electronTrayInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(startTrayInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(stopTrayInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
