/**
 * This file is auto-generated. Do not edit manually.
 * Generated by: scripts/generate-explicit-di-registration.mjs
 */

import applicationInformationInjectable from "./application-information.injectable";
import buildEnvironmentInjectable from "./build-environment.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

/**
 * Register all injectables in this directory
 */
export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(applicationInformationInjectable);
  } catch (e) {}

  try {
    di.register(buildEnvironmentInjectable);
  } catch (e) {}
}
