/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import navigateToPreferenceTabInjectable from "./navigate-to-preference-tab.injectable";
import preferenceTabIsActiveInjectable from "./preference-tab-is-active.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(navigateToPreferenceTabInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(preferenceTabIsActiveInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
