/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import discoverAllKubeconfigSyncKindsInjectable from "./discover-all-sync-kinds.injectable";
import discoverKubeconfigSyncKindInjectable from "./discover-sync-kind.injectable";
import kubeconfigSyncPreferenceBlockInjectable from "./kubeconfig-sync-preference-block.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(discoverAllKubeconfigSyncKindsInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(discoverKubeconfigSyncKindInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(kubeconfigSyncPreferenceBlockInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
