/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import {
  actionForResetZoom,
  actionForToggleDevTools,
  actionForToggleFullScreen,
  actionForZoomIn,
  actionForZoomOut,
} from "./operation-system-actions.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(actionForResetZoom);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(actionForToggleDevTools);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(actionForToggleFullScreen);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(actionForZoomIn);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(actionForZoomOut);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
