/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file imports and registers all injectables from subdirectories.
 * This replaces the webpack-based auto-registration system.
 */

import editMenuItemInjectable from "./edit-menu-item.injectable";
import { registerInjectables as registerOperationSystemActionsInjectables } from "./operation-system-actions/register-injectables";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(editMenuItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerOperationSystemActionsInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
