/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import flagRendererAsLoadedInjectable from "./flag-renderer-as-loaded.injectable";
import flagRendererAsNotLoadedInjectable from "./flag-renderer-as-not-loaded.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(flagRendererAsLoadedInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(flagRendererAsNotLoadedInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
