/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import clusterStateListenerInjectable from "./listener.injectable";
import requestInitialClusterStatesInjectable from "./request-initial.injectable";
import setupClusterStateSyncInjectable from "./setup-sync.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(clusterStateListenerInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(requestInitialClusterStatesInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(setupClusterStateSyncInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
