/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import areLogsPresentInjectable from "./are-logs-present.injectable";
import callForLogsInjectable from "./call-for-logs.injectable";
import clearLogTabDataInjectable from "./clear-log-tab-data.injectable";
import createLogsTabInjectable from "./create-logs-tab.injectable";
import createPodLogsTabInjectable from "./create-pod-logs-tab.injectable";
import createWorkloadLogsTabInjectable from "./create-workload-logs-tab.injectable";
import downloadAllLogsInjectable from "./download-all-logs.injectable";
import downloadLogsInjectable from "./download-logs.injectable";
import getLogTabDataInjectable from "./get-log-tab-data.injectable";
import getLogsInjectable from "./get-logs.injectable";
import getLogsWithoutTimestampsInjectable from "./get-logs-without-timestamps.injectable";
import getRandomIdForPodLogsTabInjectable from "./get-random-id-for-pod-logs-tab.injectable";
import getTimestampSplitLogsInjectable from "./get-timestamp-split-logs.injectable";
import isLogsTabDataValidInjectable from "./is-logs-tab-data-valid.injectable";
import loadLogsInjectable from "./load-logs.injectable";
import logsViewModelInjectable from "./logs-view-model.injectable";
import reloadLogsInjectable from "./reload-logs.injectable";
import setLogTabDataInjectable from "./set-log-tab-data.injectable";
import stopLoadingLogsInjectable from "./stop-loading-logs.injectable";
import logStoreInjectable from "./store.injectable";
import logTabStoreInjectable from "./tab-store.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(areLogsPresentInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(callForLogsInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(clearLogTabDataInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(createLogsTabInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(createPodLogsTabInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(createWorkloadLogsTabInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(downloadAllLogsInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(downloadLogsInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(getLogTabDataInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(getLogsInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(getLogsWithoutTimestampsInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(getRandomIdForPodLogsTabInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(getTimestampSplitLogsInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(isLogsTabDataValidInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(loadLogsInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(logStoreInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(logTabStoreInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(logsViewModelInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(reloadLogsInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(setLogTabDataInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(stopLoadingLogsInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
