/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import grpcRouteStoreInjectable from "./grpc-route-store.injectable";
import grpcRoutesRouteComponentInjectable from "./grpc-routes-route-component.injectable";
import grpcRoutesSidebarItemInjectable from "./grpc-routes-sidebar-item.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(grpcRouteStoreInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(grpcRoutesRouteComponentInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(grpcRoutesSidebarItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
