/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import configureImmerInjectable from "./configure-immer.injectable";
import configureMobxInjectable from "./configure-mobx.injectable";
import listenUnloadInjectable from "./listen-unload.injectable";
import loadMonacoThemesInjectable from "./load-monaco-themes.injectable";
import refreshAccessibilityOnCrdChangesInjectable from "./refresh-accessibility-on-crd-changes.injectable";
import setupAutoCrdApiCreationsInjectable from "./setup-auto-crd-api-creations.injectable";
import setupAutoRegistrationInjectable from "./setup-auto-registration.injectable";
import setupCurrentClusterBroadcastInjectable from "./setup-current-cluster-broadcast.injectable";
import setupKubernetesClusterCatalogAddMenuListenerInjectable from "./setup-kubernetes-cluster-catalog-add-menu.injectable";
import setupKubernetesClusterContextMenuOpenInjectable from "./setup-kubernetes-cluster-context-menu-open.injectable";
import setupLensProxyCertificateInjectable from "./setup-lens-proxy-certificate.injectable";
import setupRootMacClassnameInjectable from "./setup-root-mac-class.injectable";
import setupWeblinkContextMenuOpenInjectable from "./setup-weblink-context-menu-open.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(configureImmerInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(configureMobxInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(listenUnloadInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(loadMonacoThemesInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(refreshAccessibilityOnCrdChangesInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(setupAutoCrdApiCreationsInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(setupAutoRegistrationInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(setupCurrentClusterBroadcastInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(setupKubernetesClusterCatalogAddMenuListenerInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(setupKubernetesClusterContextMenuOpenInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(setupLensProxyCertificateInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(setupRootMacClassnameInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(setupWeblinkContextMenuOpenInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
