/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file imports and registers all injectables from subdirectories.
 * This replaces the webpack-based auto-registration system.
 */

import { registerInjectables as registerCallForHelmManifestInjectables } from "./call-for-helm-manifest/register-injectables";
import { registerInjectables as registerCallForKubeResourcesByManifestInjectables } from "./call-for-kube-resources-by-manifest/register-injectables";
import getHelmReleaseResourcesInjectable from "./get-helm-release-resources.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(getHelmReleaseResourcesInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerCallForHelmManifestInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerCallForKubeResourcesByManifestInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
