/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import mutatingAdmissionPoliciesRouteInjectable from "./mutating-admission-policies-route.injectable";
import navigateToMutatingAdmissionPoliciesInjectable from "./navigate-to-mutating-admission-policies.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(mutatingAdmissionPoliciesRouteInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(navigateToMutatingAdmissionPoliciesInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
