/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file imports and registers all injectables from subdirectories.
 * This replaces the webpack-based auto-registration system.
 */

import { registerInjectables as registerCopyPasteFromTerminalInjectables } from "./copy-paste-from-terminal/register-injectables";
import { registerInjectables as registerTerminalFontFamilyInjectables } from "./terminal-font-family/register-injectables";
import { registerInjectables as registerTerminalFontSizeInjectables } from "./terminal-font-size/register-injectables";
import terminalPagePreferenceItemInjectable from "./terminal-page-preference-item.injectable";
import terminalPreferenceTabInjectable from "./terminal-preference-tab.injectable";
import { registerInjectables as registerTerminalShellPathInjectables } from "./terminal-shell-path/register-injectables";
import { registerInjectables as registerTerminalThemeInjectables } from "./terminal-theme/register-injectables";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(terminalPagePreferenceItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(terminalPreferenceTabInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerCopyPasteFromTerminalInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerTerminalFontFamilyInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerTerminalFontSizeInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerTerminalShellPathInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerTerminalThemeInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
