/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file imports and registers all injectables from subdirectories.
 * This replaces the webpack-based auto-registration system.
 */

import replicaSetMetricsInjectable from "./metrics.injectable";
import replicasetsRouteComponentInjectable from "./replicasets-route-component.injectable";
import { registerInjectables as registerScaleDialogInjectables } from "./scale-dialog/register-injectables";
import replicaSetsSidebarItemInjectable from "./sidebar-item.injectable";
import replicaSetStoreInjectable from "./store.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(replicaSetMetricsInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(replicaSetStoreInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(replicaSetsSidebarItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(replicasetsRouteComponentInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerScaleDialogInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
