/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import renderInjectable from "./render-application/render.injectable";
import { renderApplicationWhenApplicationIsReadyInjectable } from "./render-application/render-application-when-application-is-ready.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(renderApplicationWhenApplicationIsReadyInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(renderInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
