/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * Root registration file for main process.
 */

import { registerInjectables as registerCommonInjectables } from "./common/register-injectables";
import { registerInjectables as registerExtensionsInjectables } from "./extensions/register-injectables";
import { registerInjectables as registerFeaturesFeaturesApplicationMenuMainInjectables } from "./features/application-menu/main/register-injectables";
import { registerInjectables as registerFeaturesFeaturesClusterActivationMainInjectables } from "./features/cluster/activation/main/register-injectables";
import { registerInjectables as registerFeaturesFeaturesClusterConnectionsMainInjectables } from "./features/cluster/connections/main/register-injectables";
import { registerInjectables as registerFeaturesFeaturesClusterDeleteDialogMainInjectables } from "./features/cluster/delete-dialog/main/register-injectables";
import { registerInjectables as registerFeaturesFeaturesClusterEnumerationMainInjectables } from "./features/cluster/enumeration/main/register-injectables";
import { registerInjectables as registerFeaturesFeaturesClusterInjectables } from "./features/cluster/register-injectables";
import { registerInjectables as registerFeaturesFeaturesClusterStateSyncMainInjectables } from "./features/cluster/state-sync/main/register-injectables";
import { registerInjectables as registerFeaturesFeaturesClusterStorageMainInjectables } from "./features/cluster/storage/main/register-injectables";
import { registerInjectables as registerFeaturesFeaturesExtensionsEnabledMainInjectables } from "./features/extensions/enabled/main/register-injectables";
import { registerInjectables as registerFeaturesFeaturesExtensionsInjectables } from "./features/extensions/register-injectables";
import { registerInjectables as registerFeaturesFeaturesExtensionsStoppingMainInjectables } from "./features/extensions/stopping/main/register-injectables";
import { registerInjectables as registerFeaturesFeaturesFileSystemProvisionerMainInjectables } from "./features/file-system-provisioner/main/register-injectables";
import { registerInjectables as registerFeaturesFeaturesHelmReleasesMainInjectables } from "./features/helm-releases/main/register-injectables";
import { registerInjectables as registerFeaturesFeaturesHotbarInjectables } from "./features/hotbar/register-injectables";
import { registerInjectables as registerFeaturesFeaturesHotbarStorageMainInjectables } from "./features/hotbar/storage/main/register-injectables";
import { registerInjectables as registerFeaturesFeaturesLicensesCommonInjectables } from "./features/licenses/common/register-injectables";
import { registerInjectables as registerFeaturesFeaturesPathPickingDialogMainInjectables } from "./features/path-picking-dialog/main/register-injectables";
import { registerInjectables as registerFeaturesFeaturesPersistentStorageMainInjectables } from "./features/persistent-storage/main/register-injectables";
import { registerInjectables as registerFeaturesFeaturesPersistentStorageInjectables } from "./features/persistent-storage/register-injectables";
import { registerInjectables as registerFeaturesFeaturesPopulationOfLogsToAFileMainInjectables } from "./features/population-of-logs-to-a-file/main/register-injectables";
import { registerInjectables as registerFeaturesFeaturesPreferencesChildFeaturesApplicationMenuMainInjectables } from "./features/preferences/child-features/application-menu/main/register-injectables";
import { registerInjectables as registerFeaturesFeaturesPreferencesChildFeaturesTrayMainInjectables } from "./features/preferences/child-features/tray/main/register-injectables";
import { registerInjectables as registerFeaturesFeaturesPreferencesCommonInjectables } from "./features/preferences/common/register-injectables";
import { registerInjectables as registerFeaturesFeaturesShellSyncMainInjectables } from "./features/shell-sync/main/register-injectables";
import { registerInjectables as registerFeaturesFeaturesThemeSystemTypeMainInjectables } from "./features/theme/system-type/main/register-injectables";
import { registerInjectables as registerFeaturesFeaturesUserPreferencesMainInjectables } from "./features/user-preferences/main/register-injectables";
import { registerInjectables as registerFeaturesFeaturesUserPreferencesInjectables } from "./features/user-preferences/register-injectables";
import { registerInjectables as registerFeaturesFeaturesVarsBuildVersionMainInjectables } from "./features/vars/build-version/main/register-injectables";
import { registerInjectables as registerFeaturesFeaturesVarsInjectables } from "./features/vars/register-injectables";
import { registerInjectables as registerFeaturesFeaturesWeblinksMainInjectables } from "./features/weblinks/main/register-injectables";
import { registerInjectables as registerFeaturesFeaturesWeblinksInjectables } from "./features/weblinks/register-injectables";
import { registerInjectables as registerMainInjectables } from "./main/register-injectables";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  registerCommonInjectables(di);
  registerExtensionsInjectables(di);
  registerFeaturesFeaturesApplicationMenuMainInjectables(di);
  registerFeaturesFeaturesClusterInjectables(di);
  registerFeaturesFeaturesClusterActivationMainInjectables(di);
  registerFeaturesFeaturesClusterConnectionsMainInjectables(di);
  registerFeaturesFeaturesClusterDeleteDialogMainInjectables(di);
  registerFeaturesFeaturesClusterEnumerationMainInjectables(di);
  registerFeaturesFeaturesClusterStateSyncMainInjectables(di);
  registerFeaturesFeaturesClusterStorageMainInjectables(di);
  registerFeaturesFeaturesExtensionsInjectables(di);
  registerFeaturesFeaturesExtensionsEnabledMainInjectables(di);
  registerFeaturesFeaturesExtensionsStoppingMainInjectables(di);
  registerFeaturesFeaturesFileSystemProvisionerMainInjectables(di);
  registerFeaturesFeaturesHelmReleasesMainInjectables(di);
  registerFeaturesFeaturesHotbarInjectables(di);
  registerFeaturesFeaturesHotbarStorageMainInjectables(di);
  registerFeaturesFeaturesLicensesCommonInjectables(di);
  registerFeaturesFeaturesPathPickingDialogMainInjectables(di);
  registerFeaturesFeaturesPersistentStorageMainInjectables(di);
  registerFeaturesFeaturesPersistentStorageInjectables(di);
  registerFeaturesFeaturesPopulationOfLogsToAFileMainInjectables(di);
  registerFeaturesFeaturesPreferencesChildFeaturesApplicationMenuMainInjectables(di);
  registerFeaturesFeaturesPreferencesChildFeaturesTrayMainInjectables(di);
  registerFeaturesFeaturesPreferencesCommonInjectables(di);
  registerFeaturesFeaturesShellSyncMainInjectables(di);
  registerFeaturesFeaturesThemeSystemTypeMainInjectables(di);
  registerFeaturesFeaturesUserPreferencesMainInjectables(di);
  registerFeaturesFeaturesUserPreferencesInjectables(di);
  registerFeaturesFeaturesVarsInjectables(di);
  registerFeaturesFeaturesVarsBuildVersionMainInjectables(di);
  registerFeaturesFeaturesWeblinksMainInjectables(di);
  registerFeaturesFeaturesWeblinksInjectables(di);
  registerMainInjectables(di);
}
