/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * Root registration file for renderer process.
 */

import { registerInjectables as registerCommonInjectables } from "./common/register-injectables";
import { registerInjectables as registerExtensionsInjectables } from "./extensions/register-injectables";
import { registerInjectables as registerFeaturesFeaturesClusterActivationRendererInjectables } from "./features/cluster/activation/renderer/register-injectables";
import { registerInjectables as registerFeaturesFeaturesClusterDeleteDialogRendererInjectables } from "./features/cluster/delete-dialog/renderer/register-injectables";
import { registerInjectables as registerFeaturesFeaturesClusterExecuteRendererInjectables } from "./features/cluster/execute/renderer/register-injectables";
import { registerInjectables as registerFeaturesFeaturesClusterInjectables } from "./features/cluster/register-injectables";
import { registerInjectables as registerFeaturesFeaturesClusterStateSyncRendererInjectables } from "./features/cluster/state-sync/renderer/register-injectables";
import { registerInjectables as registerFeaturesFeaturesClusterStorageRendererInjectables } from "./features/cluster/storage/renderer/register-injectables";
import { registerInjectables as registerFeaturesFeaturesExtensionsEnabledRendererInjectables } from "./features/extensions/enabled/renderer/register-injectables";
import { registerInjectables as registerFeaturesFeaturesExtensionsNavigateRendererInjectables } from "./features/extensions/navigate/renderer/register-injectables";
import { registerInjectables as registerFeaturesFeaturesExtensionsInjectables } from "./features/extensions/register-injectables";
import { registerInjectables as registerFeaturesFeaturesFileSystemProvisionerRendererInjectables } from "./features/file-system-provisioner/renderer/register-injectables";
import { registerInjectables as registerFeaturesFeaturesHelmChartsChildFeaturesPreferencesRendererInjectables } from "./features/helm-charts/child-features/preferences/renderer/register-injectables";
import { registerInjectables as registerFeaturesFeaturesHelmReleasesRendererInjectables } from "./features/helm-releases/renderer/register-injectables";
import { registerInjectables as registerFeaturesFeaturesHotbarInjectables } from "./features/hotbar/register-injectables";
import { registerInjectables as registerFeaturesFeaturesHotbarStorageRendererInjectables } from "./features/hotbar/storage/renderer/register-injectables";
import { registerInjectables as registerFeaturesFeaturesLicensesInjectables } from "./features/licenses/register-injectables";
import { registerInjectables as registerFeaturesFeaturesLicensesRendererInjectables } from "./features/licenses/renderer/register-injectables";
import { registerInjectables as registerFeaturesFeaturesNamespaceFilteringRendererInjectables } from "./features/namespace-filtering/renderer/register-injectables";
import { registerInjectables as registerFeaturesFeaturesNavigationReloadPageRendererInjectables } from "./features/navigation/reload-page/renderer/register-injectables";
import { registerInjectables as registerFeaturesFeaturesPathPickingDialogRendererInjectables } from "./features/path-picking-dialog/renderer/register-injectables";
import { registerInjectables as registerFeaturesFeaturesPersistentStorageInjectables } from "./features/persistent-storage/register-injectables";
import { registerInjectables as registerFeaturesFeaturesPersistentStorageRendererInjectables } from "./features/persistent-storage/renderer/register-injectables";
import { registerInjectables as registerFeaturesFeaturesPopulationOfLogsToAFileRendererInjectables } from "./features/population-of-logs-to-a-file/renderer/register-injectables";
import { registerInjectables as registerFeaturesFeaturesPreferencesInjectables } from "./features/preferences/register-injectables";
import { registerInjectables as registerFeaturesFeaturesPreferencesRendererInjectables } from "./features/preferences/renderer/register-injectables";
import { registerInjectables as registerFeaturesFeaturesShellSyncRendererInjectables } from "./features/shell-sync/renderer/register-injectables";
import { registerInjectables as registerFeaturesFeaturesTerminalRendererInjectables } from "./features/terminal/renderer/register-injectables";
import { registerInjectables as registerFeaturesFeaturesThemeSystemTypeRendererInjectables } from "./features/theme/system-type/renderer/register-injectables";
import { registerInjectables as registerFeaturesFeaturesTopBarExtensionApiRendererInjectables } from "./features/top-bar/extension-api/renderer/register-injectables";
import { registerInjectables as registerFeaturesFeaturesUserPreferencesInjectables } from "./features/user-preferences/register-injectables";
import { registerInjectables as registerFeaturesFeaturesUserPreferencesRendererInjectables } from "./features/user-preferences/renderer/register-injectables";
import { registerInjectables as registerFeaturesFeaturesVarsBuildVersionRendererInjectables } from "./features/vars/build-version/renderer/register-injectables";
import { registerInjectables as registerFeaturesFeaturesVarsInjectables } from "./features/vars/register-injectables";
import { registerInjectables as registerFeaturesFeaturesWeblinksInjectables } from "./features/weblinks/register-injectables";
import { registerInjectables as registerFeaturesFeaturesWeblinksRendererInjectables } from "./features/weblinks/renderer/register-injectables";
import { registerInjectables as registerRendererInjectables } from "./renderer/register-injectables";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  registerCommonInjectables(di);
  registerExtensionsInjectables(di);
  registerFeaturesFeaturesClusterInjectables(di);
  registerFeaturesFeaturesClusterActivationRendererInjectables(di);
  registerFeaturesFeaturesClusterDeleteDialogRendererInjectables(di);
  registerFeaturesFeaturesClusterExecuteRendererInjectables(di);
  registerFeaturesFeaturesClusterStateSyncRendererInjectables(di);
  registerFeaturesFeaturesClusterStorageRendererInjectables(di);
  registerFeaturesFeaturesExtensionsInjectables(di);
  registerFeaturesFeaturesExtensionsEnabledRendererInjectables(di);
  registerFeaturesFeaturesExtensionsNavigateRendererInjectables(di);
  registerFeaturesFeaturesFileSystemProvisionerRendererInjectables(di);
  registerFeaturesFeaturesHelmChartsChildFeaturesPreferencesRendererInjectables(di);
  registerFeaturesFeaturesHelmReleasesRendererInjectables(di);
  registerFeaturesFeaturesHotbarInjectables(di);
  registerFeaturesFeaturesHotbarStorageRendererInjectables(di);
  registerFeaturesFeaturesLicensesRendererInjectables(di);
  registerFeaturesFeaturesLicensesInjectables(di);
  registerFeaturesFeaturesNamespaceFilteringRendererInjectables(di);
  registerFeaturesFeaturesNavigationReloadPageRendererInjectables(di);
  registerFeaturesFeaturesPathPickingDialogRendererInjectables(di);
  registerFeaturesFeaturesPersistentStorageRendererInjectables(di);
  registerFeaturesFeaturesPersistentStorageInjectables(di);
  registerFeaturesFeaturesPopulationOfLogsToAFileRendererInjectables(di);
  registerFeaturesFeaturesPreferencesRendererInjectables(di);
  registerFeaturesFeaturesPreferencesInjectables(di);
  registerFeaturesFeaturesShellSyncRendererInjectables(di);
  registerFeaturesFeaturesTerminalRendererInjectables(di);
  registerFeaturesFeaturesThemeSystemTypeRendererInjectables(di);
  registerFeaturesFeaturesTopBarExtensionApiRendererInjectables(di);
  registerFeaturesFeaturesUserPreferencesRendererInjectables(di);
  registerFeaturesFeaturesUserPreferencesInjectables(di);
  registerFeaturesFeaturesVarsInjectables(di);
  registerFeaturesFeaturesVarsBuildVersionRendererInjectables(di);
  registerFeaturesFeaturesWeblinksRendererInjectables(di);
  registerFeaturesFeaturesWeblinksInjectables(di);
  registerRendererInjectables(di);
}
