name: 🐛 Bug Report
description: Create a report to help us improve
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: What is the problem? A clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction steps
      description: |
        Provide steps to reproduce the behavior:
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: false

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: |
        A clear and concise description of what you expected to happen.
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: |
        If applicable, add screenshots to help explain your problem.
    validations:
      required: false

  - type: input
    id: freelens-version
    attributes:
      label: Freelens version
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: Operating system type and version
      description: |
        e.g. Windows 11, MacOS 15.3 M1 Max, Linux Ubuntu 24.04
    validations:
      required: true

  - type: input
    id: installation-method
    attributes:
      label: Installation method
      description: |
        e.g. AppImage, DEB, DMG, EXE, MSI, PKG, source
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: |
        When you run the application executable from command line you will
        see some logging output. Please paste them here.
    validations:
      required: false

  - type: textarea
    id: kubeconfig
    attributes:
      label: Kubeconfig
      description: |
        Quite often the problems are caused by malformed kubeconfig which the
        application tries to load. Please share your kubeconfig, remember to
        remove any secret and sensitive information.
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: |
        Quite often the problems are caused by malformed kubeconfig which the
        application tries to load. Please share your kubeconfig, remember to
        remove any secret and sensitive information.
    validations:
      required: false
