/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import loadEnabledExtensionsStorageInjectable from "./load-storage.injectable";
import {
  enabledExtensionsPersistentStorageVersionInitializationInjectable,
  enabledExtensionsPersistentStorageVersionStateInjectable,
} from "./storage-version.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(enabledExtensionsPersistentStorageVersionInitializationInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(enabledExtensionsPersistentStorageVersionStateInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(loadEnabledExtensionsStorageInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
