/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file imports and registers all injectables from subdirectories.
 * This replaces the webpack-based auto-registration system.
 */

import { registerInjectables as registerEditInjectables } from "./edit/register-injectables";
import { registerInjectables as registerFileInjectables } from "./file/register-injectables";
import { registerInjectables as registerHelpInjectables } from "./help/register-injectables";
import { registerInjectables as registerSpecialMenuForMacApplicationInjectables } from "./special-menu-for-mac-application/register-injectables";
import { registerInjectables as registerViewInjectables } from "./view/register-injectables";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    registerEditInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerFileInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerHelpInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerSpecialMenuForMacApplicationInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerViewInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
