/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import daemonsetsRouteInjectable from "./daemonsets-route.injectable";
import navigateToDaemonsetsInjectable from "./navigate-to-daemonsets.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(daemonsetsRouteInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(navigateToDaemonsetsInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
