/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file imports and registers all injectables from subdirectories.
 * This replaces the webpack-based auto-registration system.
 */

import { registerInjectables as registerContextMenuInjectables } from "./context-menu/register-injectables";
import { registerInjectables as registerNavigationToBackInjectables } from "./navigation-to-back/register-injectables";
import { registerInjectables as registerNavigationToForwardInjectables } from "./navigation-to-forward/register-injectables";
import { registerInjectables as registerNavigationToHomeInjectables } from "./navigation-to-home/register-injectables";
import topBarItemsOnLeftSideInjectable from "./top-bar-items-on-left-side.injectable";
import topBarItemsOnRightSideInjectable from "./top-bar-items-on-right-side.injectable";
import { registerInjectables as registerWindowControlsInjectables } from "./window-controls/register-injectables";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(topBarItemsOnLeftSideInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(topBarItemsOnRightSideInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerContextMenuInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerNavigationToBackInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerNavigationToForwardInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerNavigationToHomeInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerWindowControlsInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
