/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file imports and registers all injectables from subdirectories.
 * This replaces the webpack-based auto-registration system.
 */

import cleanUpDeepLinkingInjectable from "./clean-up-deep-linking.injectable";
import { registerInjectables as registerDockVisibilityInjectables } from "./dock-visibility/register-injectables";
import enforceSingleApplicationInstanceInjectable from "./enforce-single-application-instance.injectable";
import setupApplicationNameInjectable from "./setup-application-name.injectable";
import setupBehaviourOnCloseOfLastWindowInjectable from "./setup-behaviour-on-close-of-last-window.injectable";
import setupCleanupOfBackendOnQuitInjectable from "./setup-cleanup-of-backend-on-quit.injectable";
import setupDeepLinkingInjectable from "./setup-deep-linking.injectable";
import setupDeveloperToolsInDevelopmentEnvironmentInjectable from "./setup-developer-tools-in-development-environment.injectable";
import setupDeviceShutdownInjectable from "./setup-device-shutdown.injectable";
import { registerInjectables as registerSetupIpcMainHandlersInjectables } from "./setup-ipc-main-handlers/register-injectables";
import setupMainWindowVisibilityAfterActivationInjectable from "./setup-main-window-visibility-after-activation.injectable";
import setupPasteHandlerInjectable from "./setup-paste-handler.injectable";
import setupRunnablesAfterWindowIsOpenedInjectable from "./setup-runnables-after-window-is-opened.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(cleanUpDeepLinkingInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(enforceSingleApplicationInstanceInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(setupApplicationNameInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(setupBehaviourOnCloseOfLastWindowInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(setupCleanupOfBackendOnQuitInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(setupDeepLinkingInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(setupDeveloperToolsInDevelopmentEnvironmentInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(setupDeviceShutdownInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(setupMainWindowVisibilityAfterActivationInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(setupPasteHandlerInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(setupRunnablesAfterWindowIsOpenedInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerDockVisibilityInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerSetupIpcMainHandlersInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
