/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import closeIpcFileLoggingListenerInjectable from "./close-ipc-logging-listener.injectable";
import createIpcFileLoggerTransportInjectable from "./create-ipc-file-transport.injectable";
import ipcFileLoggerInjectable from "./ipc-file-logger.injectable";
import ipcFileLoggingListenerInjectable from "./ipc-logging-listener.injectable";
import stopIpcLoggingInjectable from "./stop-ipc-logging.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(closeIpcFileLoggingListenerInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(createIpcFileLoggerTransportInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(ipcFileLoggerInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(ipcFileLoggingListenerInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(stopIpcLoggingInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
