/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file imports and registers all injectables from subdirectories.
 * This replaces the webpack-based auto-registration system.
 */

import { registerInjectables as registerClusterInjectables } from "./cluster/register-injectables";
import { registerInjectables as registerExtensionsInjectables } from "./extensions/register-injectables";
import { registerInjectables as registerHotbarInjectables } from "./hotbar/register-injectables";
import { registerInjectables as registerLicensesInjectables } from "./licenses/register-injectables";
import { registerInjectables as registerPersistentStorageInjectables } from "./persistent-storage/register-injectables";
import { registerInjectables as registerPreferencesInjectables } from "./preferences/register-injectables";
import { registerInjectables as registerUserPreferencesInjectables } from "./user-preferences/register-injectables";
import { registerInjectables as registerVarsInjectables } from "./vars/register-injectables";
import { registerInjectables as registerWeblinksInjectables } from "./weblinks/register-injectables";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    registerClusterInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerExtensionsInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerHotbarInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerLicensesInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerPersistentStorageInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerPreferencesInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerUserPreferencesInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerVarsInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerWeblinksInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
