/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import extensionsRootInjectable from "./extensions-root.injectable";
import forgetInstalledExtensionInjectable from "./forget-installed-extension.injectable";
import installedExtensionsStateInjectable from "./installed-extensions-state.injectable";
import installedExtensionsPersistentStorageInjectable from "./installed-extensions-storage.injectable";
import recordInstalledExtensionInjectable from "./record-installed-extension.injectable";
import sweepOrphanedExtensionBuildsInjectable from "./sweep-orphaned-builds.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(extensionsRootInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(forgetInstalledExtensionInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(installedExtensionsPersistentStorageInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(installedExtensionsStateInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(recordInstalledExtensionInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(sweepOrphanedExtensionBuildsInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
