/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import { applicationInformationFakeInjectable } from "./application-information-fake.injectable";
import nodeEnvForTestingEnvInjectable from "./node-env.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(applicationInformationFakeInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(nodeEnvForTestingEnvInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
