/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file imports and registers all injectables from subdirectories.
 * This replaces the webpack-based auto-registration system.
 */

import deleteClusterHelmReleaseInjectable from "./delete-helm-release.injectable";
import getHelmChartReadmeInjectable from "./get-helm-chart-readme.injectable";
import getHelmChartValuesInjectable from "./get-helm-chart-values.injectable";
import getHelmChartVersionsInjectable from "./get-helm-chart-versions.injectable";
import getHelmReleaseInjectable from "./get-helm-release.injectable";
import getHelmReleaseDataInjectable from "./get-helm-release-data.injectable";
import getClusterHelmReleaseHistoryInjectable from "./get-helm-release-history.injectable";
import { registerInjectables as registerGetHelmReleaseResourcesInjectables } from "./get-helm-release-resources/register-injectables";
import getClusterHelmReleaseValuesInjectable from "./get-helm-release-values.injectable";
import installClusterHelmChartInjectable from "./install-helm-chart.injectable";
import listHelmChartsInjectable from "./list-helm-charts.injectable";
import listClusterHelmReleasesInjectable from "./list-helm-releases.injectable";
import rollbackClusterHelmReleaseInjectable from "./rollback-helm-release.injectable";
import updateHelmReleaseInjectable from "./update-helm-release.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(deleteClusterHelmReleaseInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(getClusterHelmReleaseHistoryInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(getClusterHelmReleaseValuesInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(getHelmChartReadmeInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(getHelmChartValuesInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(getHelmChartVersionsInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(getHelmReleaseDataInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(getHelmReleaseInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(installClusterHelmChartInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(listClusterHelmReleasesInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(listHelmChartsInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(rollbackClusterHelmReleaseInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(updateHelmReleaseInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerGetHelmReleaseResourcesInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
