/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file imports and registers all injectables from subdirectories.
 * This replaces the webpack-based auto-registration system.
 */

import { registerInjectables as registerKubeconfigSyncInjectables } from "./kubeconfig-sync/register-injectables";
import syncGeneralCatalogEntitiesInjectable from "./sync-general-catalog-entities.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(syncGeneralCatalogEntitiesInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerKubeconfigSyncInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
