/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import cronJobMenuInjectable from "./cron-job-menu.injectable";
import daemonsetMenuInjectable from "./daemonset-menu.injectable";
import deploymentMenuInjectable from "./deployment-menu.injectable";
import jobMenuInjectable from "./job-menu-copy.injectable";
import replicaSetMenuInjectable from "./replica-set-menu.injectable";
import serviceAccountMenuInjectable from "./service-account-menu.injectable";
import statefulsetMenuInjectable from "./statefulset-menu.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(cronJobMenuInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(daemonsetMenuInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(deploymentMenuInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(jobMenuInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(replicaSetMenuInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(serviceAccountMenuInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(statefulsetMenuInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
