/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file imports and registers all injectables from subdirectories.
 * This replaces the webpack-based auto-registration system.
 */

import { registerInjectables as registerOverviewInjectables } from "./overview/register-injectables";
import favoritesSidebarItemInjectable from "./sidebar-item.injectable";
import favoritesSidebarItemsComputedInjectable from "./sidebar-items-computed.injectable";
import favoritesStoreInjectable from "./store.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(favoritesSidebarItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(favoritesSidebarItemsComputedInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(favoritesStoreInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerOverviewInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
