/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import favoritesSidebarItemInjectable from "./favorites-sidebar-item.injectable";
import favoritesSidebarItemsComputedInjectable from "./favorites-sidebar-items-computed.injectable";
import favoritesStateInjectable from "./favorites-state.injectable";
import favoritesStorageInjectable from "./favorites-storage.injectable";
import favoritesStoreInjectable from "./favorites-store.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(favoritesSidebarItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(favoritesSidebarItemsComputedInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(favoritesStateInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(favoritesStorageInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(favoritesStoreInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
