/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import getPersistentVolumesByStorageClassInjectable from "./get-persistent-volumes-by-storage-class.injectable";
import persistentVolumesRouteComponentInjectable from "./persistent-volumes-route-component.injectable";
import persistentVolumesSidebarItemInjectable from "./persistent-volumes-sidebar-item.injectable";
import persistentVolumeStoreInjectable from "./store.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(getPersistentVolumesByStorageClassInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(persistentVolumeStoreInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(persistentVolumesRouteComponentInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(persistentVolumesSidebarItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
