/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import navigateToPortForwardsInjectable from "./navigate-to-port-forwards.injectable";
import portForwardsRouteInjectable from "./port-forwards-route.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(navigateToPortForwardsInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(portForwardsRouteInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
