/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import kubernetesClusterDetailsItemInjectable from "./kubernetes-cluster-details.injectable";
import weblinkDetailsItemInjectable from "./weblink-details.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(kubernetesClusterDetailsItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(weblinkDetailsItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
