/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file imports and registers all injectables from subdirectories.
 * This replaces the webpack-based auto-registration system.
 */

import defaultWelcomeRouteComponentInjectable from "./default-welcome-route-component.injectable";
import newVersionNotificationInjectable from "./new-version-notification.injectable";
import { registerInjectables as registerWelcomeMenuItemsInjectables } from "./welcome-menu-items/register-injectables";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(defaultWelcomeRouteComponentInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(newVersionNotificationInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerWelcomeMenuItemsInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
