/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import customResourceDefinitionsInjectable from "./definitions.injectable";
import customResourceDefinitionGroupsSidebarItemsComputedInjectable from "./groups-sidebar-items-computed.injectable";
import customResourceDefinitionGroupsSidebarItemsRegistratorInjectable from "./groups-sidebar-items-registrator.injectable";
import customResourceDefinitionsRouteComponentInjectable from "./route-component.injectable";
import selectedCustomResourceDefinitionGroupsUrlParamInjectable from "./selected-groups-url-param.injectable";
import customResourceDefinitionsSidebarItemInjectable from "./sidebar-item.injectable";
import customResourceDefinitionStoreInjectable from "./store.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(customResourceDefinitionGroupsSidebarItemsComputedInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(customResourceDefinitionGroupsSidebarItemsRegistratorInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(customResourceDefinitionStoreInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(customResourceDefinitionsInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(customResourceDefinitionsRouteComponentInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(customResourceDefinitionsSidebarItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(selectedCustomResourceDefinitionGroupsUrlParamInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
