/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import createAuthorizationApiInjectable from "./create-authorization-api.injectable";
import createCanIInjectable from "./create-can-i.injectable";
import createCoreApiInjectable from "./create-core-api.injectable";
import createRequestNamespaceListPermissionsInjectable from "./create-request-namespace-list-permissions.injectable";
import createListNamespacesInjectable from "./list-namespaces.injectable";
import loadKubeconfigInjectable from "./load-kubeconfig.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(createAuthorizationApiInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(createCanIInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(createCoreApiInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(createListNamespacesInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(createRequestNamespaceListPermissionsInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(loadKubeconfigInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
