/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import getClusterInfoToolInjectable from "./get-cluster-info.injectable";
import getEventsToolInjectable from "./get-events.injectable";
import getResourceToolInjectable from "./get-resource.injectable";
import listResourcesToolInjectable from "./list-resources.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(getClusterInfoToolInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(getEventsToolInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(getResourceToolInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(listResourcesToolInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
