/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import navigateToRolesInjectable from "./navigate-to-roles.injectable";
import rolesRouteInjectable from "./roles-route.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(navigateToRolesInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(rolesRouteInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
