/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import kubeObjectStatusTextRegistratorInjectable from "./kube-object-status-text-registrator.injectable";
import kubeObjectStatusTextsInjectable from "./kube-object-status-texts.injectable";
import kubeObjectStatusTextsForObjectInjectable from "./kube-object-status-texts-for-object.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(kubeObjectStatusTextRegistratorInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(kubeObjectStatusTextsForObjectInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(kubeObjectStatusTextsInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
