/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import extensionPackageRootDirectoryInjectable from "./extension-package-root-directory.injectable";
import forkPnpmInjectable from "./fork-pnpm.injectable";
import installExtensionInjectable from "./install-extension.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(extensionPackageRootDirectoryInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(forkPnpmInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(installExtensionInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
