/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file imports and registers all injectables from subdirectories.
 * This replaces the webpack-based auto-registration system.
 */

import { registerInjectables as registerExtensionDiscoveryInjectables } from "./extension-discovery/register-injectables";
import { registerInjectables as registerExtensionInstallationStateStoreInjectables } from "./extension-installation-state-store/register-injectables";
import { registerInjectables as registerExtensionLoaderInjectables } from "./extension-loader/register-injectables";
import { registerInjectables as registerExtensionPackagesRootInjectables } from "./extension-packages-root/register-injectables";
import extensionsInjectable from "./extensions.injectable";
import { registerInjectables as registerInstallExtensionInjectables } from "./install-extension/register-injectables";
import mainExtensionsInjectable from "./main-extensions.injectable";
import rendererExtensionsInjectable from "./renderer-extensions.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(extensionsInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(mainExtensionsInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(rendererExtensionsInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerExtensionDiscoveryInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerExtensionInstallationStateStoreInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerExtensionLoaderInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerExtensionPackagesRootInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerInstallExtensionInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
