/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file imports and registers all injectables from subdirectories.
 * This replaces the webpack-based auto-registration system.
 */

import { registerInjectables as registerPublicHelmRepositoriesInjectables } from "./public-helm-repositories/register-injectables";
import { registerInjectables as registerSelectHelmRepositoryInjectables } from "./select-helm-repository/register-injectables";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    registerPublicHelmRepositoriesInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerSelectHelmRepositoryInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
