/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import verticalPodAutoscalersSidebarItemInjectable from "./sidebar-item.injectable";
import verticalPodAutoscalerStoreInjectable from "./store.injectable";
import verticalPodAutoscalersRouteComponentInjectable from "./vertical-pod-autoscalers-route-component.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(verticalPodAutoscalerStoreInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(verticalPodAutoscalersRouteComponentInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(verticalPodAutoscalersSidebarItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
