/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import requestHelmReleaseInjectable from "./request-helm-release.injectable";
import requestListHelmReleasesInjectable from "./request-list-helm-releases.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(requestHelmReleaseInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(requestListHelmReleasesInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
