/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import getTrayIconPathInjectable from "./get-tray-icon-path.injectable";
import normalTrayIconInjectable from "./normal-tray-icon.injectable";
import reactiveTrayMenuIconInjectable from "./reactive.injectable";
import startReactiveTrayMenuIconInjectable from "./start-reactivity.injectable";
import stopReactiveTrayMenuIconInjectable from "./stop-reactivity.injectable";
import trayIconInjectable from "./tray-icon.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(getTrayIconPathInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(normalTrayIconInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(reactiveTrayMenuIconInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(startReactiveTrayMenuIconInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(stopReactiveTrayMenuIconInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(trayIconInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
