/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file imports and registers all injectables from subdirectories.
 * This replaces the webpack-based auto-registration system.
 */

import applicationPreferencePageInjectable from "./application-preference-page.injectable";
import applicationPreferenceTabInjectable from "./application-preference-tab.injectable";
import { registerInjectables as registerCheckForUpdatesInjectables } from "./check-for-updates/register-injectables";
import { registerInjectables as registerDeleteProtectionInjectables } from "./delete-protection/register-injectables";
import { registerInjectables as registerExtensionInstallRegistryInjectables } from "./extension-install-registry/register-injectables";
import { registerInjectables as registerHotbarAutoHideInjectables } from "./hotbar-auto-hide/register-injectables";
import { registerInjectables as registerMenuBarInjectables } from "./menu-bar/register-injectables";
import { registerInjectables as registerSidebarMenuInjectables } from "./sidebar-menu/register-injectables";
import { registerInjectables as registerStartUpInjectables } from "./start-up/register-injectables";
import { registerInjectables as registerThemeInjectables } from "./theme/register-injectables";
import { registerInjectables as registerTimezoneInjectables } from "./timezone/register-injectables";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(applicationPreferencePageInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(applicationPreferenceTabInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerCheckForUpdatesInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerDeleteProtectionInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerExtensionInstallRegistryInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerHotbarAutoHideInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerMenuBarInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerSidebarMenuInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerStartUpInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerThemeInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerTimezoneInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
