/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import execHelmEnvInjectable from "./exec-env.injectable";
import execHelmInjectable from "./exec-helm.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(execHelmEnvInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(execHelmInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
