/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file imports and registers all injectables from subdirectories.
 * This replaces the webpack-based auto-registration system.
 */

import { registerInjectables as registerConfigInjectables } from "./config/register-injectables";
import { registerInjectables as registerCustomResourcesInjectables } from "./custom-resources/register-injectables";
import { registerInjectables as registerEventsInjectables } from "./events/register-injectables";
import { registerInjectables as registerHelmInjectables } from "./helm/register-injectables";
import { registerInjectables as registerNamespacesInjectables } from "./namespaces/register-injectables";
import { registerInjectables as registerNetworkInjectables } from "./network/register-injectables";
import { registerInjectables as registerNodesInjectables } from "./nodes/register-injectables";
import { registerInjectables as registerOverviewInjectables } from "./overview/register-injectables";
import { registerInjectables as registerStorageInjectables } from "./storage/register-injectables";
import { registerInjectables as registerUserManagementInjectables } from "./user-management/register-injectables";
import { registerInjectables as registerWorkloadsInjectables } from "./workloads/register-injectables";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    registerConfigInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerCustomResourcesInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerEventsInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerHelmInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerNamespacesInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerNetworkInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerNodesInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerOverviewInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerStorageInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerUserManagementInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerWorkloadsInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
