/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file imports and registers all injectables from subdirectories.
 * This replaces the webpack-based auto-registration system.
 */

import openShellSessionInjectable from "./create-shell-session.injectable";
import { registerInjectables as registerLocalShellSessionInjectables } from "./local-shell-session/register-injectables";
import { registerInjectables as registerNodeShellSessionInjectables } from "./node-shell-session/register-injectables";
import shellSessionProcessesInjectable from "./processes.injectable";
import { registerInjectables as registerShellEnvModifierInjectables } from "./shell-env-modifier/register-injectables";
import shellSessionEnvsInjectable from "./shell-envs.injectable";
import spawnPtyInjectable from "./spawn-pty.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(openShellSessionInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(shellSessionEnvsInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(shellSessionProcessesInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(spawnPtyInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerLocalShellSessionInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerNodeShellSessionInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerShellEnvModifierInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
