/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import deleteClusterDialogClusterFrameChildComponentInjectable from "./delete-cluster-dialog-cluster-frame-child-component.injectable";
import isInLocalKubeconfigInjectable from "./is-in-local-kubeconfig.injectable";
import openDeleteClusterDialogInjectable from "./open.injectable";
import saveKubeconfigInjectable from "./save-kubeconfig.injectable";
import deleteClusterDialogStateInjectable from "./state.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(deleteClusterDialogClusterFrameChildComponentInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(deleteClusterDialogStateInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(isInLocalKubeconfigInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(openDeleteClusterDialogInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(saveKubeconfigInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
