/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import {
  actionForHide,
  actionForHideOthers,
  actionForServices,
  actionForUnhide,
} from "./operation-system-actions.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(actionForHide);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(actionForHideOthers);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(actionForServices);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(actionForUnhide);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
