/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import getDetailsUrlInjectable from "./get-details-url.injectable";
import getMaybeDetailsUrlInjectable from "./get-maybe-details-url.injectable";
import hideDetailsInjectable from "./hide-details.injectable";
import kubeDetailsUrlParamInjectable from "./kube-details-url.injectable";
import kubeSelectedUrlParamInjectable from "./kube-selected-url.injectable";
import showDetailsInjectable from "./show-details.injectable";
import toggleKubeDetailsPaneInjectable from "./toggle-details.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(getDetailsUrlInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(getMaybeDetailsUrlInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(hideDetailsInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(kubeDetailsUrlParamInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(kubeSelectedUrlParamInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(showDetailsInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(toggleKubeDetailsPaneInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
