/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file imports and registers all injectables from subdirectories.
 * This replaces the webpack-based auto-registration system.
 */

import lensProtocolRouterMainInjectable from "./lens-protocol-router-main.injectable";
import { registerInjectables as registerOpenDeepLinkForUrlInjectables } from "./open-deep-link-for-url/register-injectables";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(lensProtocolRouterMainInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerOpenDeepLinkForUrlInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
