/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import clusterRolesRouteInjectable from "./cluster-roles-route.injectable";
import navigateToClusterRolesInjectable from "./navigate-to-cluster-roles.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(clusterRolesRouteInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(navigateToClusterRolesInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
