/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import tcpRouteStoreInjectable from "./tcp-route-store.injectable";
import tcpRoutesRouteComponentInjectable from "./tcp-routes-route-component.injectable";
import tcpRoutesSidebarItemInjectable from "./tcp-routes-sidebar-item.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(tcpRouteStoreInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(tcpRoutesRouteComponentInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(tcpRoutesSidebarItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
