/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import { defaultEnterDurationForAnimatedInjectable } from "./default-enter-duration.injectable";
import { defaultLeaveDurationForAnimatedInjectable } from "./default-leave-duration.injectable";
import { requestAnimationFrameInjectable } from "./request-animation-frame.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(defaultEnterDurationForAnimatedInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(defaultLeaveDurationForAnimatedInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(requestAnimationFrameInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
