/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file imports and registers all injectables from subdirectories.
 * This replaces the webpack-based auto-registration system.
 */

import { registerInjectables as registerCrdGroupInjectables } from "./crd-group/register-injectables";
import crdPreferencePageInjectable from "./crd-preference-page.injectable";
import crdPreferenceTabInjectable from "./crd-preference-tab.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(crdPreferencePageInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(crdPreferenceTabInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerCrdGroupInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
