/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import navigateToValidatingAdmissionPolicyBindingsInjectable from "./navigate-to-validating-admission-policy-bindings.injectable";
import validatingAdmissionPolicyBindingsRouteInjectable from "./validating-admission-policy-bindings-route.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(navigateToValidatingAdmissionPolicyBindingsInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(validatingAdmissionPolicyBindingsRouteInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
