/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file imports and registers all injectables from subdirectories.
 * This replaces the webpack-based auto-registration system.
 */

import { registerInjectables as registerApplicationWindowInjectables } from "./application-window/register-injectables";
import { registerInjectables as registerCurrentClusterFrameInjectables } from "./current-cluster-frame/register-injectables";
import getVisibleWindowsInjectable from "./get-visible-windows.injectable";
import navigateInjectable from "./navigate.injectable";
import navigateForExtensionInjectable from "./navigate-for-extension.injectable";
import reloadCurrentApplicationWindowInjectable from "./reload-current-application-window.injectable";
import showApplicationWindowInjectable from "./show-application-window.injectable";
import { registerInjectables as registerSplashWindowInjectables } from "./splash-window/register-injectables";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(getVisibleWindowsInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(navigateForExtensionInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(navigateInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(reloadCurrentApplicationWindowInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(showApplicationWindowInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerApplicationWindowInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerCurrentClusterFrameInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerSplashWindowInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
