/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import applicationWindowStateInjectable from "./application-window-state.injectable";
import createApplicationWindowInjectable from "./create-application-window.injectable";
import createElectronWindowInjectable from "./create-electron-window.injectable";
import createFirstApplicationWindowInjectable from "./create-first-application-window.injectable";
import createLensWindowInjectable from "./create-lens-window.injectable";
import getCurrentApplicationWindowInjectable from "./get-current-application-window.injectable";
import sessionCertificateVerifierInjectable from "./session-certificate-verifier.injectable";
import waitUntilBundledExtensionsAreLoadedInjectable from "./wait-until-bundled-extensions-are-loaded.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(applicationWindowStateInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(createApplicationWindowInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(createElectronWindowInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(createFirstApplicationWindowInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(createLensWindowInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(getCurrentApplicationWindowInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(sessionCertificateVerifierInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(waitUntilBundledExtensionsAreLoadedInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
