/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import customThemeColorsPreferenceBlockInjectable from "./custom-theme-colors-preference-block.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try { di.register(customThemeColorsPreferenceBlockInjectable); } catch (e) { /* Ignore duplicate registration */ }
}
