/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import computeKubeconfigDiffInjectable from "./compute-diff.injectable";
import configToModelsInjectable from "./config-to-models.injectable";
import diffChangedKubeconfigInjectable from "./diff-changed-kubeconfig.injectable";
import kubeconfigSyncLoggerInjectable from "./logger.injectable";
import kubeconfigSyncManagerInjectable from "./manager.injectable";
import watchKubeconfigFileChangesInjectable from "./watch-file-changes.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(computeKubeconfigDiffInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(configToModelsInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(diffChangedKubeconfigInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(kubeconfigSyncLoggerInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(kubeconfigSyncManagerInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(watchKubeconfigFileChangesInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
