/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import navigateToWorkloadsOverviewInjectable from "./navigate-to-workloads-overview.injectable";
import workloadsOverviewRouteInjectable from "./workloads-overview-route.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(navigateToWorkloadsOverviewInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(workloadsOverviewRouteInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
