/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import addKubeconfigSyncAsEntitySourceInjectable from "./add-source.injectable";
import startKubeConfigSyncInjectable from "./start-kube-config-sync.injectable";
import stopKubeConfigSyncInjectable from "./stop-kube-config-sync.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(addKubeconfigSyncAsEntitySourceInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(startKubeConfigSyncInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(stopKubeConfigSyncInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
