/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file imports and registers all injectables from subdirectories.
 * This replaces the webpack-based auto-registration system.
 */

import { registerInjectables as registerAddDialogInjectables } from "./add-dialog/register-injectables";
import rolesRouteComponentInjectable from "./roles-route-component.injectable";
import rolesSidebarItemInjectable from "./roles-sidebar-item.injectable";
import roleStoreInjectable from "./store.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(roleStoreInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(rolesRouteComponentInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(rolesSidebarItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerAddDialogInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
