/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import { podsAgeColumnInjectable } from "./pods-age-column.injectable";
import { podsContainersColumnInjectable } from "./pods-containers-column.injectable";
import { podsUsedCpuColumnInjectable } from "./pods-cpu-usage-column.injectable";
import { podsipColumnInjectable } from "./pods-ip-column.injectable";
import { podsLogsButtonColumnInjectable } from "./pods-logs-button-column.injectable";
import { podsUsedMemoryColumnInjectable } from "./pods-memory-usage-column.injectable";
import { podsNameColumnInjectable } from "./pods-name-column.injectable";
import { podsNamespaceColumnInjectable } from "./pods-namespace-column.injectable";
import { podsNodeColumnInjectable } from "./pods-node-column.injectable";
import { podsOwnersColumnInjectable } from "./pods-owners-column.injectable";
import { podsQosColumnInjectable } from "./pods-qos-column.injectable";
import { podsRestartsColumnInjectable } from "./pods-restarts-column.injectable";
import { podsStatusColumnInjectable } from "./pods-status-column.injectable";
import { podsStatusIconColumnInjectable } from "./pods-status-icon-column.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(podsAgeColumnInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(podsContainersColumnInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(podsLogsButtonColumnInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(podsNameColumnInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(podsNamespaceColumnInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(podsNodeColumnInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(podsOwnersColumnInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(podsQosColumnInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(podsRestartsColumnInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(podsStatusColumnInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(podsStatusIconColumnInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(podsUsedCpuColumnInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(podsUsedMemoryColumnInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(podsipColumnInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
