/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import shouldBaseStoreDisableSyncInIpcListenerInjectable from "./disable-sync-in-ipc-listener.injectable";
import baseStoreIpcChannelPrefixInjectable from "./ipc-channel-prefix.injectable";
import persistStateToConfigInjectable from "./persist-state-to-config.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(baseStoreIpcChannelPrefixInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(persistStateToConfigInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(shouldBaseStoreDisableSyncInIpcListenerInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
