/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import cancelStreamListenerInjectable from "./cancel-stream-listener.injectable";
import chatRequestListenerInjectable from "./chat-request-listener.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(cancelStreamListenerInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(chatRequestListenerInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
