/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file imports and registers all injectables from subdirectories.
 * This replaces the webpack-based auto-registration system.
 */

import navigateToFrontPageInjectable from "./navigate-to-front-page.injectable";
import { registerInjectables as registerRoutesInjectables } from "./routes/register-injectables";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(navigateToFrontPageInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerRoutesInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
