/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file imports and registers all injectables from subdirectories.
 * This replaces the webpack-based auto-registration system.
 */

import statefulSetMetricsInjectable from "./metrics.injectable";
import { registerInjectables as registerScaleInjectables } from "./scale/register-injectables";
import statefulSetsSidebarItemInjectable from "./sidebar-item.injectable";
import statefulsetsRouteComponentInjectable from "./statefulsets-route-component.injectable";
import statefulSetStoreInjectable from "./store.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(statefulSetMetricsInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(statefulSetStoreInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(statefulSetsSidebarItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(statefulsetsRouteComponentInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerScaleInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
