/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file imports and registers all injectables from subdirectories.
 * This replaces the webpack-based auto-registration system.
 */

import { registerInjectables as registerAddClusterInjectables } from "./add-cluster/register-injectables";
import { registerInjectables as registerCatalogInjectables } from "./catalog/register-injectables";
import { registerInjectables as registerClusterInjectables } from "./cluster/register-injectables";
import { registerInjectables as registerClusterViewInjectables } from "./cluster-view/register-injectables";
import { registerInjectables as registerEntitySettingsInjectables } from "./entity-settings/register-injectables";
import { registerInjectables as registerExtensionsInjectables } from "./extensions/register-injectables";
import { registerInjectables as registerWelcomeInjectables } from "./welcome/register-injectables";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    registerAddClusterInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerCatalogInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerClusterInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerClusterViewInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerEntitySettingsInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerExtensionsInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerWelcomeInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
