/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import helmReleasesRouteInjectable from "./helm-releases-route.injectable";
import navigateToHelmReleasesInjectable from "./navigate-to-helm-releases.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(helmReleasesRouteInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(navigateToHelmReleasesInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
