/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file imports and registers all injectables from subdirectories.
 * This replaces the webpack-based auto-registration system.
 */

import frameRoutingIdInjectable from "./frame-routing-id.injectable";
import { registerInjectables as registerWebFrameInjectables } from "./web-frame/register-injectables";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(frameRoutingIdInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerWebFrameInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
