/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file imports and registers all injectables from subdirectories.
 * This replaces the webpack-based auto-registration system.
 */

import commandContainerClusterFrameChildComponentInjectable from "./command-container-cluster-frame-child-component.injectable";
import commandContainerRootFrameChildComponentInjectable from "./command-container-root-frame-child-component.injectable";
import commandOverlayInjectable from "./command-overlay.injectable";
import { registerInjectables as registerRegisteredCommandsInjectables } from "./registered-commands/register-injectables";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(commandContainerClusterFrameChildComponentInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(commandContainerRootFrameChildComponentInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(commandOverlayInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerRegisteredCommandsInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
