/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import cronJobsWorkloadInjectable from "./cron-jobs-workload.injectable";
import daemonsetsWorkloadInjectable from "./daemonsets-workload.injectable";
import deploymentsWorkloadInjectable from "./deployments-workload.injectable";
import jobsWorkloadInjectable from "./jobs-workload.injectable";
import podsWorkloadInjectable from "./pods-workload.injectable";
import replicasetsWorkloadInjectable from "./replicasets-workload.injectable";
import statefulsetsWorkloadInjectable from "./statefulsets-workload.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(cronJobsWorkloadInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(daemonsetsWorkloadInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(deploymentsWorkloadInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(jobsWorkloadInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(podsWorkloadInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(replicasetsWorkloadInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(statefulsetsWorkloadInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
