/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import extensionEntryPointNameInjectable from "./entry-point-name.injectable";
import extensionShouldBeEnabledForClusterFrameInjectable from "./extension-should-be-enabled-for-cluster-frame.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(extensionEntryPointNameInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(extensionShouldBeEnabledForClusterFrameInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
