/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import closeRendererLogFileInjectable from "./close-renderer-log-file.injectable";
import ipcLogTransportInjectable from "./ipc-transport.injectable";
import rendererLogFileIdInjectable from "./renderer-log-file-id.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(closeRendererLogFileInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(ipcLogTransportInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(rendererLogFileIdInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
