/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import attemptInstallInjectable from "./attempt-install.injectable";
import createTempFilesAndValidateInjectable from "./create-temp-files-and-validate.injectable";
import getExtensionDestFolderInjectable from "./get-extension-dest-folder.injectable";
import unpackExtensionInjectable from "./unpack-extension.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(attemptInstallInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(createTempFilesAndValidateInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(getExtensionDestFolderInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(unpackExtensionInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
