/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import addHelmRepositoryInjectable from "./add-helm-repository.injectable";
import selectHelmRepositoryInjectable from "./select-helm-repository.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(addHelmRepositoryInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(selectHelmRepositoryInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
