/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import releaseChannelInjectable from "./release-channel.injectable";
import semanticBuildVersionInjectable from "./semantic-build-version.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(releaseChannelInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(semanticBuildVersionInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
