/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import disableHardwareAccelerationInjectable from "./disable-hardware-acceleration.injectable";
import electronDialogInjectable from "./electron-dialog.injectable";
import focusApplicationInjectable from "./focus-application.injectable";
import forceAppExitInjectable from "./force-app-exit.injectable";
import getBuildVersionInjectable from "./get-build-version.injectable";
import getCommandLineSwitchInjectable from "./get-command-line-switch.injectable";
import getElectronThemeInjectable from "./get-electron-theme.injectable";
import isAutoUpdatingInjectable from "./is-auto-updating.injectable";
import nativeThemeInjectable from "./native-theme.injectable";
import powerMonitorInjectable from "./power-monitor.injectable";
import requestSingleInstanceLockInjectable from "./request-single-instance-lock.injectable";
import requestQuitOfAppInjectable from "./require-quit.injectable";
import setLoginItemSettingsInjectable from "./set-login-item-settings.injectable";
import shouldStartHiddenInjectable from "./should-start-hidden.injectable";
import showErrorPopupInjectable from "./show-error-popup.injectable";
import showMessagePopupInjectable from "./show-message-popup.injectable";
import showOpenDialogInjectable from "./show-open-dialog.injectable";
import syncThemeFromOperatingSystemInjectable from "./sync-theme-from-operating-system.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(disableHardwareAccelerationInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(electronDialogInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(focusApplicationInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(forceAppExitInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(getBuildVersionInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(getCommandLineSwitchInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(getElectronThemeInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(isAutoUpdatingInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(nativeThemeInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(powerMonitorInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(requestQuitOfAppInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(requestSingleInstanceLockInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(setLoginItemSettingsInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(shouldStartHiddenInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(showErrorPopupInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(showMessagePopupInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(showOpenDialogInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(syncThemeFromOperatingSystemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
