/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file imports and registers all injectables from subdirectories.
 * This replaces the webpack-based auto-registration system.
 */

import { registerInjectables as registerFilesInjectables } from "./files/register-injectables";
import { registerInjectables as registerHelmInjectables } from "./helm/register-injectables";
import { registerInjectables as registerKubeconfigRouteInjectables } from "./kubeconfig-route/register-injectables";
import { registerInjectables as registerMetricsInjectables } from "./metrics/register-injectables";
import { registerInjectables as registerPortForwardInjectables } from "./port-forward/register-injectables";
import { registerInjectables as registerResourceApplierInjectables } from "./resource-applier/register-injectables";
import { registerInjectables as registerVersionsInjectables } from "./versions/register-injectables";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    registerFilesInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerHelmInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerKubeconfigRouteInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerMetricsInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerPortForwardInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerResourceApplierInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerVersionsInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
