/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import consoleLoggerTransportInjectable from "./console-transport.injectable";
import fileLoggerTransportInjectable from "./file-transport.injectable";
import logLevelInjectable from "./level.injectable";
import logOnQuitOfBackendInjectable from "./log-on-quit.injectable";
import logVersionOnStartInjectable from "./log-on-start.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(consoleLoggerTransportInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(fileLoggerTransportInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(logLevelInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(logOnQuitOfBackendInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(logVersionOnStartInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
