/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import clearInstallChartTabDataInjectable from "./clear-install-chart-tab-data.injectable";
import createInstallChartTabInjectable from "./create-install-chart-tab.injectable";
import getRandomInstallChartTabIdInjectable from "./get-random-install-chart-tab-id.injectable";
import installChartModelInjectable from "./install-chart-model.injectable";
import installChartTabStoreInjectable from "./store.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(clearInstallChartTabDataInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(createInstallChartTabInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(getRandomInstallChartTabIdInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(installChartModelInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(installChartTabStoreInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
