/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import backendTlsPoliciesRouteComponentInjectable from "./backend-tls-policies-route-component.injectable";
import backendTlsPoliciesSidebarItemInjectable from "./backend-tls-policies-sidebar-item.injectable";
import backendTlsPolicyStoreInjectable from "./backend-tls-policy-store.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(backendTlsPoliciesRouteComponentInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(backendTlsPoliciesSidebarItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(backendTlsPolicyStoreInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
