/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import computedChannelInjectable from "./computed-channel/computed-channel.injectable";
import {
  computedChannelAdministrationChannel,
  computedChannelAdministrationListenerInjectable,
} from "./computed-channel/computed-channel-administration-channel.injectable";
import { duplicateChannelObserverGuardInjectable } from "./computed-channel/duplicate-channel-observer-guard.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(computedChannelAdministrationChannel);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(computedChannelAdministrationListenerInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(computedChannelInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(duplicateChannelObserverGuardInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
