/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file imports and registers all injectables from subdirectories.
 * This replaces the webpack-based auto-registration system.
 */

import closeLensProxyOnQuitInjectable from "./close-on-quit.injectable";
import getClusterForRequestInjectable from "./get-cluster-for-request.injectable";
import lensProxyInjectable from "./lens-proxy.injectable";
import lensProxyCertificateRequestHandlerInjectable from "./lens-proxy-certificate-request-handler.injectable";
import lensProxyPortInjectable from "./lens-proxy-port.injectable";
import { registerInjectables as registerProxyFunctionsInjectables } from "./proxy-functions/register-injectables";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(closeLensProxyOnQuitInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(getClusterForRequestInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(lensProxyCertificateRequestHandlerInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(lensProxyInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(lensProxyPortInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerProxyFunctionsInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
