/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file imports and registers all injectables from subdirectories.
 * This replaces the webpack-based auto-registration system.
 */

import { registerInjectables as registerPageFiltersInjectables } from "./page-filters/register-injectables";
import itemListLayoutStorageInjectable from "./storage.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(itemListLayoutStorageInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerPageFiltersInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
