/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file imports and registers all injectables from subdirectories.
 * This replaces the webpack-based auto-registration system.
 */

import { registerInjectables as registerPersistentVolumeClaimsInjectables } from "./persistent-volume-claims/register-injectables";
import { registerInjectables as registerPersistentVolumesInjectables } from "./persistent-volumes/register-injectables";
import { registerInjectables as registerStorageClassesInjectables } from "./storage-classes/register-injectables";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    registerPersistentVolumeClaimsInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerPersistentVolumesInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerStorageClassesInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
