/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import computeShellEnvironmentInjectable from "./compute-shell-environment.injectable";
import computeUnixShellEnvironmentInjectable from "./compute-unix-shell-environment.injectable";
import emitShellSyncFailedInjectable from "./emit-failure.injectable";
import processEnvInjectable from "./env.injectable";
import processExecPathInjectable from "./execPath.injectable";
import setupShellInjectable from "./setup-shell.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(computeShellEnvironmentInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(computeUnixShellEnvironmentInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(emitShellSyncFailedInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(processEnvInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(processExecPathInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(setupShellInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
