/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file imports and registers all injectables from subdirectories.
 * This replaces the webpack-based auto-registration system.
 */

import { registerInjectables as registerHandlersInjectables } from "./handlers/register-injectables";
import kubeObjectHandlersInjectable from "./handlers.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(kubeObjectHandlersInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerHandlersInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
