/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import limitRangesRouteInjectable from "./limit-ranges-route.injectable";
import navigateToLimitRangesInjectable from "./navigate-to-limit-ranges.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(limitRangesRouteInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(navigateToLimitRangesInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
