/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file imports and registers all injectables from subdirectories.
 * This replaces the webpack-based auto-registration system.
 */

import { registerInjectables as registerClusterRoleBindingsInjectables } from "./cluster-role-bindings/register-injectables";
import { registerInjectables as registerClusterRolesInjectables } from "./cluster-roles/register-injectables";
import { registerInjectables as registerPodSecurityPoliciesInjectables } from "./pod-security-policies/register-injectables";
import { registerInjectables as registerRoleBindingsInjectables } from "./role-bindings/register-injectables";
import { registerInjectables as registerRolesInjectables } from "./roles/register-injectables";
import { registerInjectables as registerServiceAccountsInjectables } from "./service-accounts/register-injectables";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    registerClusterRoleBindingsInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerClusterRolesInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerPodSecurityPoliciesInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerRoleBindingsInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerRolesInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerServiceAccountsInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
