/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import clearUpgradeChartTabDataInjectable from "./clear-upgrade-chart-tab-data.injectable";
import createUpgradeChartTabInjectable from "./create-upgrade-chart-tab.injectable";
import getRandomUpgradeChartTabIdInjectable from "./get-random-upgrade-chart-tab-id.injectable";
import upgradeChartTabStoreInjectable from "./store.injectable";
import upgradeChartTabDataInjectable from "./tab-data.injectable";
import upgradeChartModelInjectable from "./upgrade-chart-model.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(clearUpgradeChartTabDataInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(createUpgradeChartTabInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(getRandomUpgradeChartTabIdInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(upgradeChartModelInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(upgradeChartTabDataInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(upgradeChartTabStoreInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
