/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import closeDockTabInjectable from "./close-dock-tab.injectable";
import createDockTabInjectable from "./create-dock-tab.injectable";
import dockStorageInjectable from "./dock-storage.injectable";
import renameTabInjectable from "./rename-tab.injectable";
import selectDockTabInjectable from "./select-dock-tab.injectable";
import dockStoreInjectable from "./store.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(closeDockTabInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(createDockTabInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(dockStorageInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(dockStoreInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(renameTabInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(selectDockTabInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
