/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import daemonSetMetricsInjectable from "./daemon-set-details-metrics.injectable";
import deploymentMetricsInjectable from "./deployment-details-metrics.injectable";
import { getMetricsKubeObjectDetailItemInjectable } from "./get-metrics-kube-object-detail-item.injectable";
import ingressMetricsInjectable from "./ingress-details-metrics.injectable";
import jobMetricsInjectable from "./job-details-metrics.injectable";
import namespaceMetricsInjectable from "./namespace-details-metrics.injectable";
import nodeMetricsInjectable from "./node-details-metrics.injectable";
import persistentVolumeClaimMetricsInjectable from "./persistent-volume-claim-metrics.injectable";
import podMetricsInjectable from "./pod-details-pod-metrics.injectable";
import replicaSetMetricsInjectable from "./replica-set-details-metrics.injectable";
import statefulSetMetricsInjectable from "./stateful-set-details-metrics.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(daemonSetMetricsInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(deploymentMetricsInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(getMetricsKubeObjectDetailItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(ingressMetricsInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(jobMetricsInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(namespaceMetricsInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(nodeMetricsInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(persistentVolumeClaimMetricsInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(podMetricsInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(replicaSetMetricsInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(statefulSetMetricsInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
