/**
 * Copyright (c) Freelens Authors. All rights reserved.
 * Copyright (c) OpenLens Authors. All rights reserved.
 * Licensed under MIT License. See LICENSE in root directory for more information.
 */

// What is left of the extension-API surface check after #2451.
//
// This file used to enumerate about a hundred names by hand with
// `toHaveProperty`. That list checked no types, covered an arbitrary subset of
// the surface, and went stale the moment somebody changed the API without
// remembering it existed. The three things it was reaching for now live where
// they can actually fail:
//
//  - **types** — `packages/fixture-extension/src/contract-types.ts` names types
//    out of all three namespaces in real signatures, compiled against the built
//    `dist/extension-api.d.ts`. A re-export that disappears breaks that build,
//    and a symbol re-exported as a value but not as a type is not nameable
//    there at all (#2365), which a property list cannot see.
//  - **behaviour and instance identity** — `./fixture-extension.test.tsx` loads
//    the fixture's built bundle and drives it through the host.
//  - **runtime presence of the whole surface** — below. The fixture only reaches
//    the handful of symbols it uses, so the rest still needs an assertion.
//
// The lists below were generated once from the built surface and checked in.
// They are deliberately not snapshots: `pnpm test:unit:updatesnapshot` is a
// routine command in this repository, and a contract breach that can be
// absolved by running it is not guarded at all. Changing the exported surface
// has to be an edit to this file, made on purpose and read in review — which is
// the whole of what this test is for. To regenerate a list after an intended
// change, run the suite and copy the received value out of the diff.
//
// This is a stopgap for #2366. An extractor-produced, git-tracked API report is
// the right instrument: it records what we *promise* rather than what we happen
// to export, and TSDoc `@public` / `@internal` would let the incidental names
// below — most of them arriving through the star re-exports in
// `renderer-api/components.ts` — be excluded rather than merely written down.
// Until that exists, this file is the only thing that makes a change to the
// surface visible. Do not copy the pattern elsewhere; extend #2366 instead.
//
// `Object.keys` of a namespace is its export list; it is sorted here rather
// than relied on to come out sorted, because the namespace objects are produced
// by the bundler's interop and follow source order. Type-only namespaces
// (`Common.Types`) contribute nothing at runtime and are empty below, which is
// itself the point: those are covered at the type level and nowhere else.

import * as extensions from "../extension-api";

const commonNames = ["App", "Catalog", "Clusters", "EventBus", "Proxy", "Store", "Types", "Util", "logger"];

const commonNamespaceNames = {
  App: [
    "Preferences",
    "appName",
    "getEnabledExtensions",
    "isFlatpak",
    "isLinux",
    "isMac",
    "isSnap",
    "isWindows",
    "issuesTrackerUrl",
    "lensBuildEnvironment",
    "version",
  ],
  Catalog: [
    "CatalogCategory",
    "CatalogEntity",
    "GeneralEntity",
    "KubernetesCluster",
    "WebLink",
    "categoryVersion",
    "kubernetesClusterCategory",
  ],
  Clusters: ["ClusterConnectionStatus", "isClusterConnectionStatus"],
  EventBus: ["appEventBus"],
  Proxy: ["resolveSystemProxy"],
  Store: ["ExtensionStore"],
  Types: [],
  Util: [
    "HashSet",
    "ObservableHashSet",
    "Ordering",
    "WrappedAbortController",
    "array",
    "backoffCaller",
    "base64",
    "bindPredicate",
    "buildURL",
    "buildURLPositional",
    "byOrderNumber",
    "byValue",
    "bytesToUnits",
    "chainSignal",
    "computedAnd",
    "computedOr",
    "convertKubectlJsonPathToNodeJsonPath",
    "cpuUnitsToNumber",
    "cssNames",
    "cssVar",
    "debouncePromise",
    "delay",
    "displayMode",
    "disposer",
    "formatDuration",
    "formatInTimeZone",
    "formatJSONValue",
    "formatRelativeTime",
    "getAppVersion",
    "getAvailableTimezones",
    "getConvertedParts",
    "getOrInsert",
    "getOrInsertMap",
    "getOrInsertSet",
    "getOrInsertSetFor",
    "getOrInsertWith",
    "getOrInsertWithAsync",
    "guessUserTimezone",
    "hasDefinedTupleValue",
    "hasDefiniteField",
    "hasOptionalTypedProperty",
    "hasOwnProperties",
    "hasOwnProperty",
    "hasStringProperty",
    "hasTypedProperty",
    "includes",
    "interval",
    "isAbortError",
    "isBoolean",
    "isBuffer",
    "isChildProcessError",
    "isDefined",
    "isErrnoException",
    "isExecException",
    "isExecFileException",
    "isFunction",
    "isIso8601DateString",
    "isMiddleClick",
    "isNumber",
    "isObject",
    "isPromiseLike",
    "isPromiseSettledFulfilled",
    "isPromiseSettledRejected",
    "isReactNode",
    "isRecord",
    "isRequestError",
    "isString",
    "isTypedArray",
    "iter",
    "json",
    "listTarEntries",
    "lowerAndPluralize",
    "makeIterableIterator",
    "metricUnitsToNumber",
    "namedCaptures",
    "noop",
    "object",
    "observableCrate",
    "onKeyboardShortcut",
    "onceDefined",
    "openBrowser",
    "openExternal",
    "prevDefault",
    "put",
    "readFileFromTar",
    "readonly",
    "rectifyOrdering",
    "rejectPromiseBy",
    "safeJSONPathValue",
    "setAndGet",
    "setTimeoutFor",
    "sortBySemverVersion",
    "sortCompare",
    "stopPropagation",
    "strictGet",
    "strictSet",
    "toCamelCase",
    "toggle",
    "tuple",
    "unionPATHs",
    "unitsToBytes",
    "urlBuilderFor",
    "waitUntilDefined",
    "withConcurrencyLimit",
  ],
};

const mainNames = ["Catalog", "Ipc", "K8s", "K8sApi", "LensExtension", "Navigation", "Power", "Util"];

const mainNamespaceNames = {
  Catalog: ["catalogCategories", "catalogEntities", "getAllClusters", "getClusterById"],
  K8s: [
    "applyOnCluster",
    "deleteOnCluster",
    "getResource",
    "patchOnCluster",
    "queryAllClusters",
    "queryCluster",
    "queryClusters",
  ],
  K8sApi: [
    "ClusterRole",
    "ClusterRoleBinding",
    "ConfigMap",
    "CronJob",
    "CustomResourceDefinition",
    "DaemonSet",
    "Deployment",
    "DeploymentApi",
    "Endpoint",
    "EndpointSlice",
    "HorizontalPodAutoscaler",
    "Ingress",
    "IngressApi",
    "Job",
    "KubeApi",
    "KubeEvent",
    "KubeJsonApi",
    "KubeObject",
    "KubeObjectStore",
    "KubeStatus",
    "LensExtensionKubeObject",
    "LimitRange",
    "Namespace",
    "NetworkPolicy",
    "Node",
    "NodesApi",
    "PersistentVolume",
    "PersistentVolumeClaim",
    "PersistentVolumeClaimsApi",
    "Pod",
    "PodDisruptionBudget",
    "PodsApi",
    "PriorityClass",
    "ReplicaSet",
    "ResourceQuota",
    "Role",
    "RoleBinding",
    "Secret",
    "Service",
    "ServiceAccount",
    "StatefulSet",
    "StorageClass",
    "apiManager",
    "createKubeObject",
    "createResourceStack",
    "forCluster",
    "getPodsByOwnerId",
    "isJsonApiData",
    "isJsonApiDataList",
    "isKubeJsonApiListMetadata",
    "isKubeJsonApiMetadata",
    "isKubeObjectNonSystem",
    "isKubeStatusData",
    "isPartialJsonApiData",
    "isPartialJsonApiMetadata",
    "stringifyLabels",
  ],
  Navigation: ["navigate"],
  Power: ["onResume", "onShutdown", "onSuspend"],
  Util: [
    "HashSet",
    "ObservableHashSet",
    "Ordering",
    "WrappedAbortController",
    "array",
    "backoffCaller",
    "base64",
    "bindPredicate",
    "buildURL",
    "buildURLPositional",
    "byOrderNumber",
    "byValue",
    "bytesToUnits",
    "chainSignal",
    "computedAnd",
    "computedOr",
    "convertKubectlJsonPathToNodeJsonPath",
    "cpuUnitsToNumber",
    "cssNames",
    "cssVar",
    "debouncePromise",
    "delay",
    "displayMode",
    "disposer",
    "fetch",
    "formatDuration",
    "formatInTimeZone",
    "formatJSONValue",
    "formatRelativeTime",
    "getAppVersion",
    "getAvailableTimezones",
    "getConvertedParts",
    "getOrInsert",
    "getOrInsertMap",
    "getOrInsertSet",
    "getOrInsertSetFor",
    "getOrInsertWith",
    "getOrInsertWithAsync",
    "guessUserTimezone",
    "hasDefinedTupleValue",
    "hasDefiniteField",
    "hasOptionalTypedProperty",
    "hasOwnProperties",
    "hasOwnProperty",
    "hasStringProperty",
    "hasTypedProperty",
    "includes",
    "interval",
    "isAbortError",
    "isBoolean",
    "isBuffer",
    "isChildProcessError",
    "isDefined",
    "isErrnoException",
    "isExecException",
    "isExecFileException",
    "isFunction",
    "isIso8601DateString",
    "isMiddleClick",
    "isNumber",
    "isObject",
    "isPromiseLike",
    "isPromiseSettledFulfilled",
    "isPromiseSettledRejected",
    "isReactNode",
    "isRecord",
    "isRequestError",
    "isString",
    "isTypedArray",
    "iter",
    "json",
    "listTarEntries",
    "lowerAndPluralize",
    "makeIterableIterator",
    "metricUnitsToNumber",
    "namedCaptures",
    "noop",
    "object",
    "observableCrate",
    "onKeyboardShortcut",
    "onceDefined",
    "openBrowser",
    "openExternal",
    "prevDefault",
    "put",
    "readFileFromTar",
    "readonly",
    "rectifyOrdering",
    "rejectPromiseBy",
    "safeJSONPathValue",
    "setAndGet",
    "setTimeoutFor",
    "sortBySemverVersion",
    "sortCompare",
    "stopPropagation",
    "strictGet",
    "strictSet",
    "toCamelCase",
    "toggle",
    "tuple",
    "unionPATHs",
    "unitsToBytes",
    "urlBuilderFor",
    "waitUntilDefined",
    "withConcurrencyLimit",
  ],
};

const rendererNames = ["Catalog", "Component", "Ipc", "K8s", "K8sApi", "LensExtension", "Navigation", "Theme", "Util"];

const rendererNamespaceNames = {
  Catalog: [
    "CatalogEntityRegistry",
    "activeCluster",
    "catalogCategories",
    "catalogEntities",
    "getActiveCluster",
    "getAllClusters",
    "getClusterById",
  ],
  Component: [
    "AddRemoveButtons",
    "Avatar",
    "Badge",
    "BadgeBoolean",
    "BarChart",
    "Button",
    "Chart",
    "ChartKind",
    "Checkbox",
    "CommandOverlay",
    "ConfirmDialog",
    "Countdown",
    "Dialog",
    "Drawer",
    "DrawerItem",
    "DrawerItemLabels",
    "DrawerParamToggler",
    "DrawerTitle",
    "DropFileInput",
    "Dropdown",
    "DurationAbsoluteTimestamp",
    "EditableList",
    "EventDetails",
    "Events",
    "FileInput",
    "FilePicker",
    "FormSwitch",
    "Gutter",
    "HorizontalLine",
    "Icon",
    "Input",
    "InputValidators",
    "ItemListLayout",
    "KubeObjectAge",
    "KubeObjectConditionsDrawer",
    "KubeObjectConditionsList",
    "KubeObjectDetails",
    "KubeObjectListLayout",
    "KubeObjectMenu",
    "KubeObjectMeta",
    "LineProgress",
    "LinkToClusterRole",
    "LinkToConfigMap",
    "LinkToJob",
    "LinkToNamespace",
    "LinkToNode",
    "LinkToObject",
    "LinkToPod",
    "LinkToPriorityClass",
    "LinkToReplicaSet",
    "LinkToRole",
    "LinkToRuntimeClass",
    "LinkToSecret",
    "LinkToServiceAccount",
    "LinkToStorageClass",
    "LocaleDate",
    "MainLayout",
    "Map",
    "MarkdownViewer",
    "MaybeLink",
    "Menu",
    "MenuActions",
    "MenuContext",
    "MenuItem",
    "MonacoEditor",
    "NamespaceSelect",
    "NamespaceSelectBadge",
    "NamespaceSelectBadgeNonInjected",
    "NamespaceSelectFilter",
    "NoItems",
    "NotificationStatus",
    "Notifications",
    "OverLimitStyle",
    "OverSizeLimitStyle",
    "OverTotalSizeLimitStyle",
    "PageLayout",
    "PathPicker",
    "PieChart",
    "PodCharts",
    "PodDetailsList",
    "Radio",
    "RadioGroup",
    "ReactiveDuration",
    "RenderDelay",
    "ResourceMetrics",
    "ResourceMetricsContext",
    "SearchInput",
    "SearchInputUrl",
    "Select",
    "SettingLayout",
    "Slider",
    "Spinner",
    "StatusBrick",
    "Stepper",
    "SubMenu",
    "SubTitle",
    "Switch",
    "Switcher",
    "Tab",
    "TabLayout",
    "Table",
    "TableCell",
    "TableHead",
    "TableRow",
    "Tabs",
    "TerminalStore",
    "TimeRangedResourceMetrics",
    "Tooltip",
    "TooltipPosition",
    "TreeGroup",
    "TreeItem",
    "TreeView",
    "VirtualList",
    "WithTooltip",
    "Wizard",
    "WizardLayout",
    "WizardStep",
    "asyncInputValidator",
    "cpuOptions",
    "createTerminalTab",
    "getBooleanClass",
    "getBooleanText",
    "inputValidator",
    "isAsyncValidator",
    "isSvg",
    "logTabStore",
    "memoryOptions",
    "notificationsStore",
    "onMultiSelectFor",
    "podMetricTabs",
    "resizingAnchorProps",
    "sortConditions",
    "terminalStore",
    "unionInputValidatorsAsync",
    "withTooltip",
  ],
  K8s: [
    "applyOnCluster",
    "deleteOnCluster",
    "getResource",
    "patchOnCluster",
    "queryAllClusters",
    "queryCluster",
    "queryClusters",
  ],
  K8sApi: [
    "CRDResourceStore",
    "CRDStore",
    "ClusterRole",
    "ClusterRoleBinding",
    "ClusterRoleBindingStore",
    "ClusterRoleStore",
    "ConfigMap",
    "ConfigMapStore",
    "ConfigMapsStore",
    "CronJob",
    "CronJobStore",
    "CustomResourceDefinition",
    "CustomResourceDefinitionStore",
    "CustomResourceStore",
    "DaemonSet",
    "DaemonSetStore",
    "Deployment",
    "DeploymentApi",
    "DeploymentStore",
    "Endpoint",
    "EndpointSlice",
    "EndpointSliceStore",
    "EndpointStore",
    "EndpointsStore",
    "EventStore",
    "HPAStore",
    "HorizontalPodAutoscaler",
    "HorizontalPodAutoscalerStore",
    "Ingress",
    "IngressApi",
    "IngressClassStore",
    "IngressStore",
    "Job",
    "JobStore",
    "KubeApi",
    "KubeEvent",
    "KubeJsonApi",
    "KubeObject",
    "KubeObjectStatusLevel",
    "KubeObjectStore",
    "KubeStatus",
    "LensExtensionKubeObject",
    "LimitRange",
    "LimitRangeStore",
    "LimitRangesStore",
    "Namespace",
    "NamespaceStore",
    "NetworkPolicy",
    "NetworkPolicyStore",
    "Node",
    "NodeStore",
    "NodesApi",
    "NodesStore",
    "PersistentVolume",
    "PersistentVolumeClaim",
    "PersistentVolumeClaimStore",
    "PersistentVolumeClaimsApi",
    "PersistentVolumeStore",
    "PersistentVolumesStore",
    "Pod",
    "PodDisruptionBudget",
    "PodDisruptionBudgetStore",
    "PodDisruptionBudgetsStore",
    "PodStore",
    "PodsApi",
    "PodsStore",
    "PriorityClass",
    "PriorityClassStore",
    "PriorityClassStoreStore",
    "ReplicaSet",
    "ReplicaSetStore",
    "ResourceQuota",
    "ResourceQuotaStore",
    "ResourceQuotasStore",
    "Role",
    "RoleBinding",
    "RoleBindingStore",
    "RoleBindingsStore",
    "RoleStore",
    "RolesStore",
    "Secret",
    "SecretStore",
    "SecretsStore",
    "Service",
    "ServiceAccount",
    "ServiceAccountStore",
    "ServiceAccountsStore",
    "ServiceStore",
    "StatefulSet",
    "StatefulSetStore",
    "StorageClass",
    "StorageClassStore",
    "VerticalPodAutoscalerStore",
    "VolumeClaimStore",
    "apiManager",
    "clusterRoleApi",
    "clusterRoleBindingApi",
    "clusterRoleBindingStore",
    "clusterRoleStore",
    "configMapApi",
    "configMapStore",
    "crdApi",
    "crdStore",
    "createKubeObject",
    "createResourceStack",
    "cronJobApi",
    "cronJobStore",
    "daemonSetApi",
    "daemonSetStore",
    "deploymentApi",
    "deploymentStore",
    "endpointApi",
    "endpointSliceApi",
    "endpointSliceStore",
    "endpointStore",
    "eventApi",
    "eventStore",
    "forCluster",
    "getPodsByOwnerId",
    "hpaApi",
    "hpaStore",
    "ingressApi",
    "ingressStore",
    "isAllowedResource",
    "isJsonApiData",
    "isJsonApiDataList",
    "isKubeJsonApiListMetadata",
    "isKubeJsonApiMetadata",
    "isKubeObjectNonSystem",
    "isKubeStatusData",
    "isPartialJsonApiData",
    "isPartialJsonApiMetadata",
    "jobApi",
    "jobStore",
    "limitRangeApi",
    "limitRangeStore",
    "namespaceStore",
    "namespacesApi",
    "networkPolicyApi",
    "networkPolicyStore",
    "nodesApi",
    "nodesMetricsApi",
    "nodesStore",
    "pcApi",
    "pcStore",
    "pdbApi",
    "pdbStore",
    "persistentVolumeApi",
    "persistentVolumeStore",
    "podsApi",
    "podsMetricsApi",
    "podsStore",
    "priorityClassApi",
    "pvcApi",
    "pvcStore",
    "replicaSetApi",
    "replicaSetStore",
    "requestMetrics",
    "resourceQuotaApi",
    "resourceQuotaStore",
    "roleApi",
    "roleBindingApi",
    "roleBindingStore",
    "roleStore",
    "secretsApi",
    "secretsStore",
    "serviceAccountsApi",
    "serviceAccountsStore",
    "serviceApi",
    "serviceStore",
    "statefulSetApi",
    "statefulSetStore",
    "storageClassApi",
    "storageClassStore",
    "stringifyLabels",
    "vpaApi",
    "vpaStore",
  ],
  Navigation: [
    "createPageParam",
    "getDetailsUrl",
    "getMaybeDetailsUrl",
    "hideDetails",
    "hideEntityDetails",
    "isActiveRoute",
    "navigate",
    "showDetails",
    "showEntityDetails",
  ],
  Theme: ["activeTheme"],
  Util: [
    "HashSet",
    "ObservableHashSet",
    "Ordering",
    "WrappedAbortController",
    "array",
    "backoffCaller",
    "base64",
    "bindPredicate",
    "buildURL",
    "buildURLPositional",
    "byOrderNumber",
    "byValue",
    "bytesToUnits",
    "chainSignal",
    "computedAnd",
    "computedOr",
    "convertKubectlJsonPathToNodeJsonPath",
    "cpuUnitsToNumber",
    "cssNames",
    "cssVar",
    "debouncePromise",
    "delay",
    "displayMode",
    "disposer",
    "fetch",
    "formatDuration",
    "formatInTimeZone",
    "formatJSONValue",
    "formatRelativeTime",
    "getAppVersion",
    "getAvailableTimezones",
    "getConvertedParts",
    "getOrInsert",
    "getOrInsertMap",
    "getOrInsertSet",
    "getOrInsertSetFor",
    "getOrInsertWith",
    "getOrInsertWithAsync",
    "guessUserTimezone",
    "hasDefinedTupleValue",
    "hasDefiniteField",
    "hasOptionalTypedProperty",
    "hasOwnProperties",
    "hasOwnProperty",
    "hasStringProperty",
    "hasTypedProperty",
    "includes",
    "interval",
    "isAbortError",
    "isBoolean",
    "isBuffer",
    "isChildProcessError",
    "isDefined",
    "isErrnoException",
    "isExecException",
    "isExecFileException",
    "isFunction",
    "isIso8601DateString",
    "isMiddleClick",
    "isNumber",
    "isObject",
    "isPromiseLike",
    "isPromiseSettledFulfilled",
    "isPromiseSettledRejected",
    "isReactNode",
    "isRecord",
    "isRequestError",
    "isString",
    "isTypedArray",
    "iter",
    "json",
    "listTarEntries",
    "lowerAndPluralize",
    "makeIterableIterator",
    "metricUnitsToNumber",
    "namedCaptures",
    "noop",
    "object",
    "observableCrate",
    "onKeyboardShortcut",
    "onceDefined",
    "openBrowser",
    "openExternal",
    "prevDefault",
    "put",
    "readFileFromTar",
    "readonly",
    "rectifyOrdering",
    "rejectPromiseBy",
    "safeJSONPathValue",
    "setAndGet",
    "setTimeoutFor",
    "sortBySemverVersion",
    "sortCompare",
    "stopPropagation",
    "strictGet",
    "strictSet",
    "toCamelCase",
    "toggle",
    "tuple",
    "unionPATHs",
    "unitsToBytes",
    "urlBuilderFor",
    "waitUntilDefined",
    "withConcurrencyLimit",
  ],
};

describe("extensions API surface", () => {
  it("exports Common, Main and Renderer", () => {
    expect(Object.keys(extensions).sort()).toEqual(["Common", "Main", "Renderer"]);
  });

  it("exports a stable set of names from Common", () => {
    expect(Object.keys(extensions.Common).sort()).toEqual(commonNames);
  });

  it("exports a stable set of names from each Common namespace", () => {
    expect({
      App: Object.keys(extensions.Common.App).sort(),
      Catalog: Object.keys(extensions.Common.Catalog).sort(),
      Clusters: Object.keys(extensions.Common.Clusters).sort(),
      EventBus: Object.keys(extensions.Common.EventBus).sort(),
      Proxy: Object.keys(extensions.Common.Proxy).sort(),
      Store: Object.keys(extensions.Common.Store).sort(),
      Types: Object.keys(extensions.Common.Types).sort(),
      Util: Object.keys(extensions.Common.Util).sort(),
    }).toEqual(commonNamespaceNames);
  });

  it("exports a stable set of names from Main", () => {
    expect(Object.keys(extensions.Main).sort()).toEqual(mainNames);
  });

  it("exports a stable set of names from each Main namespace", () => {
    expect({
      Catalog: Object.keys(extensions.Main.Catalog).sort(),
      K8s: Object.keys(extensions.Main.K8s).sort(),
      K8sApi: Object.keys(extensions.Main.K8sApi).sort(),
      Navigation: Object.keys(extensions.Main.Navigation).sort(),
      Power: Object.keys(extensions.Main.Power).sort(),
      Util: Object.keys(extensions.Main.Util).sort(),
    }).toEqual(mainNamespaceNames);
  });

  it("exports a stable set of names from Renderer", () => {
    expect(Object.keys(extensions.Renderer).sort()).toEqual(rendererNames);
  });

  it("exports a stable set of names from each Renderer namespace", () => {
    expect({
      Catalog: Object.keys(extensions.Renderer.Catalog).sort(),
      Component: Object.keys(extensions.Renderer.Component).sort(),
      K8s: Object.keys(extensions.Renderer.K8s).sort(),
      K8sApi: Object.keys(extensions.Renderer.K8sApi).sort(),
      Navigation: Object.keys(extensions.Renderer.Navigation).sort(),
      Theme: Object.keys(extensions.Renderer.Theme).sort(),
      Util: Object.keys(extensions.Renderer.Util).sort(),
    }).toEqual(rendererNamespaceNames);
  });
});
