/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file imports and registers all injectables from subdirectories.
 * This replaces the webpack-based auto-registration system.
 */

import binaryNameInjectable from "./binary-name.injectable";
import bundledBinaryPathInjectable from "./bundled-binary-path.injectable";
import getLatestVersionInjectable from "./get-latest-version.injectable";
import openLinkInBrowserInjectable from "./open-link-in-browser.injectable";
import platformSpecificVersionInjectable from "./platform-specific-version.injectable";
import randomBytesInjectable from "./random-bytes.injectable";
import { registerInjectables as registerSyncBoxInjectables } from "./sync-box/register-injectables";
import { registerInjectables as registerWithErrorLoggingInjectables } from "./with-error-logging/register-injectables";
import { registerInjectables as registerWithOrphanPromiseInjectables } from "./with-orphan-promise/register-injectables";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(binaryNameInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(bundledBinaryPathInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(getLatestVersionInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(openLinkInBrowserInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(platformSpecificVersionInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(randomBytesInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerSyncBoxInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerWithErrorLoggingInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerWithOrphanPromiseInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
