/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file imports and registers all injectables from subdirectories.
 * This replaces the webpack-based auto-registration system.
 */

import { registerInjectables as registerClosePreferencesInjectables } from "./close-preferences/register-injectables";
import { registerInjectables as registerComplianceForLegacyExtensionApiInjectables } from "./compliance-for-legacy-extension-api/register-injectables";
import { registerInjectables as registerPreferenceItemsInjectables } from "./preference-items/register-injectables";
import { registerInjectables as registerPreferenceNavigationInjectables } from "./preference-navigation/register-injectables";
import PreferencesRouteComponent from "./preferences-route-component.injectable";
import preferencesRouteComponentInjectable from "./preferences-route-component-for-legacy-extensions.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(PreferencesRouteComponent);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(preferencesRouteComponentInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerClosePreferencesInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerComplianceForLegacyExtensionApiInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerPreferenceItemsInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerPreferenceNavigationInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
