/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import { clusterApiInjectable } from "./specifics/cluster.api.injectable";
import { clusterRoleApiInjectable } from "./specifics/cluster-role.api.injectable";
import { clusterRoleBindingApiInjectable } from "./specifics/cluster-role-binding.api.injectable";
import { componentStatusApiInjectable } from "./specifics/component-status.api.injectable";
import { configMapApiInjectable } from "./specifics/config-map.api.injectable";
import { cronJobApiInjectable } from "./specifics/cron-job.api.injectable";
import { customResourceDefinitionApiInjectable } from "./specifics/custom-resource-definition.api.injectable";
import { daemonSetApiInjectable } from "./specifics/daemon-set.api.injectable";
import { deploymentApiInjectable } from "./specifics/deployment.api.injectable";
import { endpointsApiInjectable } from "./specifics/endpoint.api.injectable";
import { endpointSliceApiInjectable } from "./specifics/endpoint-slice.api.injectable";
import { kubeEventApiInjectable } from "./specifics/event.api.injectable";
import { horizontalPodAutoscalerApiInjectable } from "./specifics/horizontal-pod-autoscaler.api.injectable";
import { ingressApiInjectable } from "./specifics/ingress.api.injectable";
import { ingressClassApiInjectable } from "./specifics/ingress-class.api.injectable";
import { jobApiInjectable } from "./specifics/job.api.injectable";
import { leaseApiInjectable } from "./specifics/lease.api.injectable";
import { limitRangeApiInjectable } from "./specifics/limit-range.api.injectable";
import { maybeKubeApiInjectable } from "./specifics/maybe-kube-api.injectable";
import { mutatingWebhookConfigurationApiInjectable } from "./specifics/mutating-webhook-configuration-api.injectable";
import { namespaceApiInjectable } from "./specifics/namespace.api.injectable";
import { networkPolicyApiInjectable } from "./specifics/network-policy.api.injectable";
import { nodeApiInjectable } from "./specifics/node.api.injectable";
import { nodeMetricsApiInjectable } from "./specifics/node-metrics.api.injectable";
import { persistentVolumeApiInjectable } from "./specifics/persistent-volume.api.injectable";
import { persistentVolumeClaimApiInjectable } from "./specifics/persistent-volume-claim.api.injectable";
import { podApiInjectable } from "./specifics/pod.api.injectable";
import { podDisruptionBudgetApiInjectable } from "./specifics/pod-disruption-budget.api.injectable";
import { podMetricsApiInjectable } from "./specifics/pod-metrics.api.injectable";
import { podSecurityPolicyApiInjectable } from "./specifics/pod-security-policy.api.injectable";
import { priorityClassApiInjectable } from "./specifics/priority-class.api.injectable";
import { replicaSetApiInjectable } from "./specifics/replica-set.api.injectable";
import { replicationControllerApiInjectable } from "./specifics/replication-controller.api.injectable";
import { resourceQuotaApiInjectable } from "./specifics/resource-quota.api.injectable";
import { roleApiInjectable } from "./specifics/role.api.injectable";
import { roleBindingApiInjectable } from "./specifics/role-binding.api.injectable";
import { runtimeClassApiInjectable } from "./specifics/runtime-class.api.injectable";
import { secretApiInjectable } from "./specifics/secret.api.injectable";
import { selfSubjectRulesReviewApiInjectable } from "./specifics/self-subject-rules-reviews.api.injectable";
import { serviceApiInjectable } from "./specifics/service.api.injectable";
import { serviceAccountApiInjectable } from "./specifics/service-account.api.injectable";
import { statefulSetApiInjectable } from "./specifics/stateful-set.api.injectable";
import { storageClassApiInjectable } from "./specifics/storage-class.api.injectable";
import { validatingWebhookConfigurationApiInjectable } from "./specifics/validating-webhook-configuration-api.injectable";
import { verticalPodAutoscalerApiInjectable } from "./specifics/vertical-pod-autoscaler.api.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(clusterApiInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(clusterRoleApiInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(clusterRoleBindingApiInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(componentStatusApiInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(configMapApiInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(cronJobApiInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(customResourceDefinitionApiInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(daemonSetApiInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(deploymentApiInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(endpointSliceApiInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(endpointsApiInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(horizontalPodAutoscalerApiInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(ingressApiInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(ingressClassApiInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(jobApiInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(kubeEventApiInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(leaseApiInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(limitRangeApiInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(maybeKubeApiInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(mutatingWebhookConfigurationApiInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(namespaceApiInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(networkPolicyApiInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(nodeApiInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(nodeMetricsApiInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(persistentVolumeApiInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(persistentVolumeClaimApiInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(podApiInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(podDisruptionBudgetApiInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(podMetricsApiInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(podSecurityPolicyApiInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(priorityClassApiInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(replicaSetApiInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(replicationControllerApiInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(resourceQuotaApiInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(roleApiInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(roleBindingApiInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(runtimeClassApiInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(secretApiInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(selfSubjectRulesReviewApiInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(serviceAccountApiInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(serviceApiInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(statefulSetApiInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(storageClassApiInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(validatingWebhookConfigurationApiInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(verticalPodAutoscalerApiInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
