/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file imports and registers all injectables from subdirectories.
 * This replaces the webpack-based auto-registration system.
 */

import { registerInjectables as registerElectronTrayInjectables } from "./electron-tray/register-injectables";
import { registerInjectables as registerMenuIconInjectables } from "./menu-icon/register-injectables";
import { registerInjectables as registerReactiveTrayMenuItemsInjectables } from "./reactive-tray-menu-items/register-injectables";
import { registerInjectables as registerTrayMenuItemInjectables } from "./tray-menu-item/register-injectables";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    registerElectronTrayInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerMenuIconInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerReactiveTrayMenuItemsInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerTrayMenuItemInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
