/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import createPageParamInjectable from "./create-page-param.injectable";
import focusWindowInjectable from "./focus-window.injectable";
import isActiveRouteInjectable from "./is-route-active.injectable";
import matchRouteInjectable from "./match-route.injectable";
import matchedClusterIdInjectable from "./matched-cluster-id.injectable";
import navigateInjectable from "./navigate.injectable";
import navigationChannelListenerInjectable from "./navigation-channel-listener.injectable";
import setupLoggingForNavigationInjectable from "./setup-logging-for-navigation.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(createPageParamInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(focusWindowInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(isActiveRouteInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(matchRouteInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(matchedClusterIdInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(navigateInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(navigationChannelListenerInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(setupLoggingForNavigationInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
