/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file imports and registers all injectables from subdirectories.
 * This replaces the webpack-based auto-registration system.
 */

import { registerInjectables as registerCronJobsInjectables } from "./cron-jobs/register-injectables";
import { registerInjectables as registerDaemonsetsInjectables } from "./daemonsets/register-injectables";
import { registerInjectables as registerDeploymentsInjectables } from "./deployments/register-injectables";
import { registerInjectables as registerJobsInjectables } from "./jobs/register-injectables";
import { registerInjectables as registerOverviewInjectables } from "./overview/register-injectables";
import { registerInjectables as registerPodsInjectables } from "./pods/register-injectables";
import { registerInjectables as registerReplicasetsInjectables } from "./replicasets/register-injectables";
import { registerInjectables as registerReplicationControllersInjectables } from "./replication-controllers/register-injectables";
import { registerInjectables as registerStatefulsetsInjectables } from "./statefulsets/register-injectables";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    registerCronJobsInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerDaemonsetsInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerDeploymentsInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerJobsInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerOverviewInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerPodsInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerReplicasetsInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerReplicationControllersInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerStatefulsetsInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
