# CRD Groups Configuration
Built-in:
  - apps
  - core
  - batch
  - extensions

Cert Manager:
  - cert-manager.io

Istio:
  - istio.io
  - Networking:
      - networking.istio.io
  - Security:
      - security.istio.io

KEDA:
  - keda.sh
  - Eventing:
      - eventing.keda.sh

Knative:
  - knative.dev

Kubernetes:
  - k8s.io
  - API Extensions:
      - apiextensions.k8s.io
  - API Registration:
      - apiregistration.k8s.io
  - Autoscaling:
      - autoscaling
  - Storage:
      - storage.k8s.io
  - Authentication:
      - authentication.k8s.io
  - Authorization:
      - authorization.k8s.io
  - Admission Controllers:
      - admission.k8s.io

Prometheus:
  - monitoring.coreos.com

Cloud Providers:
  Azure:
    - azure.com
    - microsoft.com
    - Service Mesh:
        - servicemesh.azure.com
    - Storage:
        - storage.azure.com
    - AKS:
        - containerservice.azure.com
    - Key Vault:
        - keyvault.azure.com
  AWS:
    - aws.amazon.com
    - amazonaws.com
  GCP:
    - cloud.google.com
    - googleapis.com

Others:
  - ""
