/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import backendLBPoliciesRouteInjectable from "./backend-lb-policies-route.injectable";
import navigateToBackendLBPoliciesInjectable from "./navigate-to-backend-lb-policies.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(backendLBPoliciesRouteInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(navigateToBackendLBPoliciesInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
