/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file imports and registers all injectables from subdirectories.
 * This replaces the webpack-based auto-registration system.
 */

import { registerInjectables as registerCatalogInjectables } from "./catalog/register-injectables";
import createStandaloneTerminalApiInjectable from "./create-standalone-terminal-api.injectable";
import createTerminalApiInjectable from "./create-terminal-api.injectable";
import defaultWebsocketApiParamsInjectable from "./default-websocket-api-params.injectable";
import { registerInjectables as registerHelpersInjectables } from "./helpers/register-injectables";
import requestClusterShellTokenInjectable from "./request-cluster-shell-token.injectable";
import requestStandaloneShellTokenInjectable from "./request-standalone-shell-token.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(createStandaloneTerminalApiInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(createTerminalApiInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(defaultWebsocketApiParamsInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(requestClusterShellTokenInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(requestStandaloneShellTokenInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerCatalogInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerHelpersInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
