/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file imports and registers all injectables from subdirectories.
 * This replaces the webpack-based auto-registration system.
 */

import callForKubeResourcesByManifestInjectable from "./call-for-kube-resources-by-manifest.injectable";
import { registerInjectables as registerExecFileWithInputInjectables } from "./exec-file-with-input/register-injectables";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(callForKubeResourcesByManifestInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerExecFileWithInputInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
