/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file imports and registers all injectables from subdirectories.
 * This replaces the webpack-based auto-registration system.
 */

import { registerInjectables as registerCreateResourceInjectables } from "./create-resource/register-injectables";
import { registerInjectables as registerDockInjectables } from "./dock/register-injectables";
import { registerInjectables as registerDockTabStoreInjectables } from "./dock-tab-store/register-injectables";
import { registerInjectables as registerEditResourceInjectables } from "./edit-resource/register-injectables";
import { registerInjectables as registerInstallChartInjectables } from "./install-chart/register-injectables";
import { registerInjectables as registerLogsInjectables } from "./logs/register-injectables";
import { registerInjectables as registerTerminalInjectables } from "./terminal/register-injectables";
import { registerInjectables as registerUpgradeChartInjectables } from "./upgrade-chart/register-injectables";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    registerCreateResourceInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerDockInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerDockTabStoreInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerEditResourceInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerInstallChartInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerLogsInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerTerminalInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerUpgradeChartInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
