/**
 * This file is auto-generated. Do not edit manually.
 * Generated by: scripts/generate-explicit-di-registration.mjs
 */

import { nodeEnvInjectable } from "./node-env.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

/**
 * Register all injectables in this directory
 */
export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(nodeEnvInjectable);
  } catch (e) {}
}
