/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file imports and registers all injectables from subdirectories.
 * This replaces the webpack-based auto-registration system.
 */

import { registerInjectables as registerHelmChartsApiInjectables } from "./helm-charts.api/register-injectables";
import { registerInjectables as registerHelmReleasesApiInjectables } from "./helm-releases.api/register-injectables";
import { registerInjectables as registerMetricsApiInjectables } from "./metrics.api/register-injectables";
import { registerInjectables as registerResourceApplierApiInjectables } from "./resource-applier.api/register-injectables";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    registerHelmChartsApiInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerHelmReleasesApiInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerMetricsApiInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerResourceApplierApiInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
