/**
 * Copyright (c) Freelens Authors. All rights reserved.
 * Licensed under MIT License. See LICENSE in root directory for more information.
 *
 * Palette based on Ayu Colors by Konstantin Pschera, licensed under the MIT License.
 * https://github.com/ayu-theme/ayu-colors
 */

import { getInjectable } from "@ogre-tools/injectable";
import { lensThemeDeclarationInjectionToken } from "./declaration";

import type { Injectable } from "@ogre-tools/injectable";
import type { ReadonlyDeep } from "type-fest";

import type { LensTheme } from "./lens-theme";

// Annotated for declaration emit; see ./declaration.ts.
const ayuMirageThemeInjectable: Injectable<LensTheme, ReadonlyDeep<LensTheme>> = getInjectable({
  id: "ayu-mirage-theme",
  instantiate: () => {
    const theme: LensTheme = {
      name: "Ayu Mirage",
      type: "dark" as const,
      description: "Ayu Mirage theme for Freelens",
      author: "Ayu Theme contributors",
      monacoTheme: "ayu-mirage" as const,
      colors: {
        blue: "#73d0ff",
        magenta: "#dfbfff",
        golden: "#ffcc66",
        halfGray: "#707a8c80",
        primary: "#ffcc66",
        textColorPrimary: "#cccac2",
        textColorSecondary: "#cccac2b3",
        textColorTertiary: "#afb7c1",
        textColorAccent: "#ffffff",
        textColorDimmed: "#707a8c80",
        borderColor: "#171b24",
        borderFaintColor: "#1a1f29",
        mainBackground: "#1f2430",
        secondaryBackground: "#242936",
        contentColor: "#282e3b",
        layoutBackground: "#1f2430",
        layoutTabsBackground: "#242936",
        layoutTabsActiveColor: "#cccac2",
        layoutTabsLineColor: "#ffcc66",
        sidebarBackground: "#1f2430",
        sidebarLogoBackground: "#242936",
        sidebarActiveColor: "#ffcc66",
        sidebarSubmenuActiveColor: "#ffcc66",
        sidebarItemHoverBackground: "#63759926",
        badgeBackgroundColor: "#ffcc66",
        buttonPrimaryBackground: "#735923",
        buttonDefaultBackground: "#707a8c33",
        buttonLightBackground: "#cccac2",
        buttonAccentBackground: "#ff6666",
        buttonDisabledBackground: "#707a8c80",
        tableBgcStripe: "#242936",
        tableBgcSelected: "#63759926",
        tableHeaderBackground: "#282e3b",
        tableHeaderColor: "#cccac2",
        tableSelectedRowColor: "#cccac2",
        helmLogoBackground: "#ffffff",
        helmStableRepo: "#87d96c",
        helmIncubatorRepo: "#ffa659",
        helmDescriptionHr: "#171b24",
        helmDescriptionBlockquoteColor: "#afb7c1",
        helmDescriptionBlockquoteBorder: "#707a8c",
        helmDescriptionBlockquoteBackground: "#282e3b",
        helmDescriptionHeaders: "#cccac2",
        helmDescriptionH6: "#707a8c",
        helmDescriptionTdBorder: "#171b24",
        helmDescriptionTrBackground: "#242936",
        helmDescriptionCodeBackground: "#707a8c1a",
        helmDescriptionPreBackground: "#181c26",
        helmDescriptionPreColor: "#cccac2",
        colorSuccess: "#87d96c",
        colorOk: "#d5ff80",
        colorInfo: "#5ccfe6",
        colorError: "#ff6666",
        colorSoftError: "#f28779",
        colorWarning: "#ffcd66",
        colorVague: "#282e3b",
        colorTerminated: "#707a8c",
        dockHeadBackground: "#1f2430",
        dockInfoBackground: "#242936",
        dockInfoBorderColor: "#171b24",
        dockEditorBackground: "#1f2430",
        dockEditorTag: "#5ccfe6",
        dockEditorKeyword: "#ffa659",
        dockEditorComment: "#6e7c8f",
        dockEditorActiveLineBackground: "#1a1f29",
        dockBadgeBackground: "#ffcc6633",
        dockTabBorderColor: "#171b24",
        dockTabActiveBackground: "#282e3b",
        logsBackground: "#1f2430",
        logsForeground: "#cccac2",
        logRowHoverBackground: "#63759926",
        dialogTextColor: "#cccac2",
        dialogBackground: "#282e3b",
        dialogHeaderBackground: "#1f2430",
        dialogFooterBackground: "#242936",
        drawerTogglerBackground: "#282e3b",
        drawerTitleText: "#cccac2",
        drawerSubtitleBackground: "#242936",
        drawerItemNameColor: "#afb7c1",
        drawerItemValueColor: "#cccac2",
        clusterMenuBackground: "#1f2430",
        clusterMenuBorderColor: "#171b24",
        clusterMenuCellBackground: "#282e3b",
        clusterMenuCellOutline: "#ffcc6666",
        clusterSettingsBackground: "#242936",
        addClusterIconColor: "#ffcc66",
        boxShadow: "#00000033",
        iconActiveColor: "#ffcc66",
        iconActiveBackground: "#63759926",
        filterAreaBackground: "#242936",
        chartLiveBarBackground: "#00000033",
        chartStripesColor: "#ffffff08",
        chartCapacityColor: "#707a8c",
        pieChartDefaultColor: "#171b24",
        inputOptionHoverColor: "#cccac2",
        inputControlBackground: "#242936",
        inputControlBorder: "#707a8c33",
        inputControlHoverBorder: "#ffcc6680",
        lineProgressBackground: "#171b24",
        radioActiveBackground: "#282e3b",
        menuActiveBackground: "#735923",
        menuSelectedOptionBgc: "#63759926",
        canvasBackground: "#1f2430",
        scrollBarColor: "#707a8c66",
        settingsBackground: "#242936",
        settingsColor: "#cccac2",
        navSelectedBackground: "#282e3b",
        navHoverColor: "#cccac2",
        hrColor: "#171b24",
        tooltipBackground: "#1c212c",
      },
      terminalColors: {
        background: "#1f2430",
        foreground: "#cccac2",
        cursor: "#ffcc66",
        cursorAccent: "#1f2430",
        selectionBackground: "#409fff40",
        selectionInactiveBackground: "#409fff21",
        black: "#0a0000",
        red: "#f06b5c",
        green: "#bfe76d",
        yellow: "#e6b752",
        blue: "#3bbbf4",
        magenta: "#d09ffd",
        cyan: "#84ceb5",
        white: "#d2d6dc",
        brightBlack: "#0a0000",
        brightRed: "#f39184",
        brightGreen: "#d5ff80",
        brightYellow: "#ffcd66",
        brightBlue: "#73d0ff",
        brightMagenta: "#dfbfff",
        brightCyan: "#95e6cb",
        brightWhite: "#e3e6ea",
      },
    };

    return theme;
  },
  injectionToken: lensThemeDeclarationInjectionToken,
});

export default ayuMirageThemeInjectable;
