/**
 * Copyright (c) Freelens Authors. All rights reserved.
 * Licensed under MIT License. See LICENSE in root directory for more information.
 *
 * Palette based on Ayu Colors by Konstantin Pschera, licensed under the MIT License.
 * https://github.com/ayu-theme/ayu-colors
 */

import { getInjectable } from "@ogre-tools/injectable";
import { lensThemeDeclarationInjectionToken } from "./declaration";

import type { Injectable } from "@ogre-tools/injectable";
import type { ReadonlyDeep } from "type-fest";

import type { LensTheme } from "./lens-theme";

// Annotated for declaration emit; see ./declaration.ts.
const ayuDarkThemeInjectable: Injectable<LensTheme, ReadonlyDeep<LensTheme>> = getInjectable({
  id: "ayu-dark-theme",
  instantiate: () => {
    const theme: LensTheme = {
      name: "Ayu Dark",
      type: "dark" as const,
      description: "Ayu Dark theme for Freelens",
      author: "Ayu Theme contributors",
      monacoTheme: "ayu-dark" as const,
      colors: {
        blue: "#59c2ff",
        magenta: "#d2a6ff",
        golden: "#e6b450",
        halfGray: "#5a637880",
        primary: "#e6b450",
        textColorPrimary: "#bfbdb6",
        textColorSecondary: "#bfbdb6b3",
        textColorTertiary: "#667381",
        textColorAccent: "#ffffff",
        textColorDimmed: "#5a637880",
        borderColor: "#1b1f29",
        borderFaintColor: "#161a24",
        mainBackground: "#0d1017",
        secondaryBackground: "#10141c",
        contentColor: "#141821",
        layoutBackground: "#0d1017",
        layoutTabsBackground: "#10141c",
        layoutTabsActiveColor: "#bfbdb6",
        layoutTabsLineColor: "#e6b450",
        sidebarBackground: "#0d1017",
        sidebarLogoBackground: "#10141c",
        sidebarActiveColor: "#e6b450",
        sidebarSubmenuActiveColor: "#e6b450",
        sidebarItemHoverBackground: "#47526640",
        badgeBackgroundColor: "#e6b450",
        buttonPrimaryBackground: "#765b24",
        buttonDefaultBackground: "#5a637833",
        buttonLightBackground: "#bfbdb6",
        buttonAccentBackground: "#d95757",
        buttonDisabledBackground: "#5a637880",
        tableBgcStripe: "#10141c",
        tableBgcSelected: "#47526640",
        tableHeaderBackground: "#141821",
        tableHeaderColor: "#bfbdb6",
        tableSelectedRowColor: "#bfbdb6",
        helmLogoBackground: "#ffffff",
        helmStableRepo: "#70bf56",
        helmIncubatorRepo: "#ff8f40",
        helmDescriptionHr: "#1b1f29",
        helmDescriptionBlockquoteColor: "#667381",
        helmDescriptionBlockquoteBorder: "#5a6378",
        helmDescriptionBlockquoteBackground: "#141821",
        helmDescriptionHeaders: "#bfbdb6",
        helmDescriptionH6: "#5a6378",
        helmDescriptionTdBorder: "#1b1f29",
        helmDescriptionTrBackground: "#10141c",
        helmDescriptionCodeBackground: "#5a63781a",
        helmDescriptionPreBackground: "#0d1017",
        helmDescriptionPreColor: "#bfbdb6",
        colorSuccess: "#70bf56",
        colorOk: "#aad94c",
        colorInfo: "#39bae6",
        colorError: "#d95757",
        colorSoftError: "#f07178",
        colorWarning: "#ffb454",
        colorVague: "#141821",
        colorTerminated: "#5a6378",
        dockHeadBackground: "#0d1017",
        dockInfoBackground: "#10141c",
        dockInfoBorderColor: "#1b1f29",
        dockEditorBackground: "#0d1017",
        dockEditorTag: "#39bae6",
        dockEditorKeyword: "#ff8f40",
        dockEditorComment: "#5a6673",
        dockEditorActiveLineBackground: "#161a24",
        dockBadgeBackground: "#e6b45033",
        dockTabBorderColor: "#1b1f29",
        dockTabActiveBackground: "#141821",
        logsBackground: "#0d1017",
        logsForeground: "#bfbdb6",
        logRowHoverBackground: "#47526640",
        dialogTextColor: "#bfbdb6",
        dialogBackground: "#141821",
        dialogHeaderBackground: "#0d1017",
        dialogFooterBackground: "#10141c",
        drawerTogglerBackground: "#141821",
        drawerTitleText: "#bfbdb6",
        drawerSubtitleBackground: "#10141c",
        drawerItemNameColor: "#667381",
        drawerItemValueColor: "#bfbdb6",
        clusterMenuBackground: "#0d1017",
        clusterMenuBorderColor: "#1b1f29",
        clusterMenuCellBackground: "#141821",
        clusterMenuCellOutline: "#e6b45066",
        clusterSettingsBackground: "#10141c",
        addClusterIconColor: "#e6b450",
        boxShadow: "#00000080",
        iconActiveColor: "#e6b450",
        iconActiveBackground: "#47526640",
        filterAreaBackground: "#10141c",
        chartLiveBarBackground: "#00000033",
        chartStripesColor: "#ffffff08",
        chartCapacityColor: "#5a6378",
        pieChartDefaultColor: "#1b1f29",
        inputOptionHoverColor: "#bfbdb6",
        inputControlBackground: "#10141c",
        inputControlBorder: "#5a637833",
        inputControlHoverBorder: "#e6b45080",
        lineProgressBackground: "#1b1f29",
        radioActiveBackground: "#141821",
        menuActiveBackground: "#765b24",
        menuSelectedOptionBgc: "#47526640",
        canvasBackground: "#0d1017",
        scrollBarColor: "#5a637866",
        settingsBackground: "#10141c",
        settingsColor: "#bfbdb6",
        navSelectedBackground: "#141821",
        navHoverColor: "#bfbdb6",
        hrColor: "#1b1f29",
        tooltipBackground: "#0f131a",
      },
      terminalColors: {
        background: "#0d1017",
        foreground: "#bfbdb6",
        cursor: "#e6b450",
        cursorAccent: "#0d1017",
        selectionBackground: "#3388ff40",
        selectionInactiveBackground: "#80b5ff26",
        black: "#0a0000",
        red: "#e6495a",
        green: "#97c142",
        yellow: "#e89d37",
        blue: "#17acf2",
        magenta: "#c385fe",
        cyan: "#84ceb5",
        white: "#ffffff",
        brightBlack: "#0a0000",
        brightRed: "#f07178",
        brightGreen: "#aad94c",
        brightYellow: "#ffb454",
        brightBlue: "#59c2ff",
        brightMagenta: "#d2a6ff",
        brightCyan: "#95e6cb",
        brightWhite: "#ffffff",
      },
    };

    return theme;
  },
  injectionToken: lensThemeDeclarationInjectionToken,
});

export default ayuDarkThemeInjectable;
