/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import helm14PrometheusProviderInjectable from "./helm-14-provider.injectable";
import helmPrometheusProviderInjectable from "./helm-provider.injectable";
import lensPrometheusProviderInjectable from "./lens-provider.injectable";
import openshiftPrometheusProviderInjectable from "./openshift-provider.injectable";
import operatorPrometheusProviderInjectable from "./operator-provider.injectable";
import stacklightPrometheusProviderInjectable from "./stacklight-provider.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(helm14PrometheusProviderInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(helmPrometheusProviderInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(lensPrometheusProviderInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(openshiftPrometheusProviderInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(operatorPrometheusProviderInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(stacklightPrometheusProviderInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
