/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file imports and registers all injectables from subdirectories.
 * This replaces the webpack-based auto-registration system.
 */

import { registerInjectables as registerComponentsInjectables } from "./components/register-injectables";
import customColumnsStorageInjectable from "./custom-columns-storage.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(customColumnsStorageInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerComponentsInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
