/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import createResourceRouteInjectable from "./create-resource-route.injectable";
import patchResourceRouteInjectable from "./patch-resource-route.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(createResourceRouteInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(patchResourceRouteInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
