/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file imports and registers all injectables from subdirectories.
 * This replaces the webpack-based auto-registration system.
 */

import createFreelensK8sProxyInjectable from "./create-freelens-k8s-proxy.injectable";
import freelensK8sProxyCertificateInjectable from "./freelens-k8s-proxy-certificate.injectable";
import freeLensK8sProxyPathInjectable from "./freelens-k8s-proxy-path.injectable";
import { registerInjectables as registerWaitUntilPortIsUsedInjectables } from "./wait-until-port-is-used/register-injectables";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(createFreelensK8sProxyInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(freeLensK8sProxyPathInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(freelensK8sProxyCertificateInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerWaitUntilPortIsUsedInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
