/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import kubectlApplyAllInjectable from "./apply-all.injectable";
import kubectlDeleteAllInjectable from "./delete-all.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(kubectlApplyAllInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(kubectlDeleteAllInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
