/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file imports and registers all injectables from subdirectories.
 * This replaces the webpack-based auto-registration system.
 */

import closeFreelensProxyOnQuitInjectable from "./close-on-quit.injectable";
import freelensProxyInjectable from "./freelens-proxy.injectable";
import freelensProxyCertificateRequestHandlerInjectable from "./freelens-proxy-certificate-request-handler.injectable";
import freelensProxyPortInjectable from "./freelens-proxy-port.injectable";
import getClusterForRequestInjectable from "./get-cluster-for-request.injectable";
import { registerInjectables as registerProxyFunctionsInjectables } from "./proxy-functions/register-injectables";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(closeFreelensProxyOnQuitInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(freelensProxyCertificateRequestHandlerInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(freelensProxyInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(freelensProxyPortInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(getClusterForRequestInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerProxyFunctionsInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
