/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import activeEntityInjectable from "./active.injectable";
import activeEntityIdInjectable from "./active-entity-id.injectable";
import catalogEnitiesInjectable from "./entities.injectable";
import activeEntityInternalClusterInjectable from "./get-active-cluster-entity.injectable";
import getEntityByIdInjectable from "./get-by-id.injectable";
import metricsDetailsComponentEnabledInjectable from "./metrics-details-component-enabled.injectable";
import enabledMetricsInjectable from "./metrics-enabled.injectable";
import catalogEntityRegistryInjectable from "./registry.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(activeEntityIdInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(activeEntityInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(activeEntityInternalClusterInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(catalogEnitiesInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(catalogEntityRegistryInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(enabledMetricsInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(getEntityByIdInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(metricsDetailsComponentEnabledInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
