/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import clusterRoleBindingDetailItemInjectable from "./cluster-role-binding-detail-item.injectable";
import clusterRoleDetailItemInjectable from "./cluster-role-detail-item.injectable";
import configMapDetailItemInjectable from "./config-map-detail-item.injectable";
import cronJobDetailItemInjectable from "./cron-job-detail-item.injectable";
import customResourceDefinitionsDetailItemInjectable from "./custom-resource-definitions-detail-item.injectable";
import daemonSetDetailItemInjectable from "./daemon-set-detail-item.injectable";
import deploymentDetailItemInjectable from "./deployment-detail-item.injectable";
import endpointSliceDetailItemInjectable from "./endpoint-slice-detail-item.injectable";
import endpointsDetailItemInjectable from "./endpoints-detail-item.injectable";
import eventsDetailItemInjectable from "./events-detail-item.injectable";
import horizontalPodAutoscalerDetailItemInjectable from "./horizontal-pod-autoscaler-detail-item.injectable";
import ingressClassDetailItemInjectable from "./ingress-class-detail-item.injectable";
import ingressDetailItemInjectable from "./ingress-detail-item.injectable";
import jobDetailItemInjectable from "./job-detail-item.injectable";
import kubeEventDetailItemInjectable from "./kube-event-detail-item.injectable";
import leaseDetailItemInjectable from "./lease-detail-item.injectable";
import limitRangeDetailItemInjectable from "./limit-range-detail-item.injectable";
import mutatingWebhookConfigurationDetailItemInjectable from "./mutating-webhook-configurations-details-item.injectable";
import namespacesDetailItemInjectable from "./namespaces-detail-item.injectable";
import networkPolicyDetailItemInjectable from "./network-policy-detail-item.injectable";
import nodeDetailItemInjectable from "./node-detail-item.injectable";
import persistentVolumeClaimDetailItemInjectable from "./persistent-volume-claim-detail-item.injectable";
import persistentVolumeDetailItemInjectable from "./persistent-volume-detail-item.injectable";
import podDetailItemInjectable from "./pod-detail-item.injectable";
import podDisruptionBudgetDetailItemInjectable from "./pod-disruption-budget-detail-item.injectable";
import podSecurityPolicyDetailItemInjectable from "./pod-security-policy-detail-item.injectable";
import priorityClassDetailItemInjectable from "./priority-class-detail-item.injectable";
import replicaSetDetailItemInjectable from "./replica-set-detail-item.injectable";
import replicationControllerDetailItemInjectable from "./replication-controller-detail-item.injectable";
import resourceQuotaDetailItemInjectable from "./resource-quota-detail-item.injectable";
import roleBindingDetailItemInjectable from "./role-binding-detail-item.injectable";
import roleDetailItemInjectable from "./role-detail-item.injectable";
import runtimeClassDetailItemInjectable from "./runtime-class-detail-item.injectable";
import secretsDetailItemInjectable from "./secrets-detail-item.injectable";
import serviceAccountDetailItemInjectable from "./service-account-detail-item.injectable";
import serviceDetailItemInjectable from "./service-detail-item.injectable";
import statefulSetDetailItemInjectable from "./stateful-set-detail-item.injectable";
import storageClassDetailItemInjectable from "./storage-class-detail-item.injectable";
import validatingWebhookConfigurationDetailItemInjectable from "./validating-webhook-configurations-details-item.injectable";
import verticalPodAutoscalerDetailItemInjectable from "./vertical-pod-autoscaler-detail-item.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(clusterRoleBindingDetailItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(clusterRoleDetailItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(configMapDetailItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(cronJobDetailItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(customResourceDefinitionsDetailItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(daemonSetDetailItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(deploymentDetailItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(endpointSliceDetailItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(endpointsDetailItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(eventsDetailItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(horizontalPodAutoscalerDetailItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(ingressClassDetailItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(ingressDetailItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(jobDetailItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(kubeEventDetailItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(leaseDetailItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(limitRangeDetailItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(mutatingWebhookConfigurationDetailItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(namespacesDetailItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(networkPolicyDetailItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(nodeDetailItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(persistentVolumeClaimDetailItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(persistentVolumeDetailItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(podDetailItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(podDisruptionBudgetDetailItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(podSecurityPolicyDetailItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(priorityClassDetailItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(replicaSetDetailItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(replicationControllerDetailItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(resourceQuotaDetailItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(roleBindingDetailItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(roleDetailItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(runtimeClassDetailItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(secretsDetailItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(serviceAccountDetailItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(serviceDetailItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(statefulSetDetailItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(storageClassDetailItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(validatingWebhookConfigurationDetailItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(verticalPodAutoscalerDetailItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
