/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file imports and registers all injectables from subdirectories.
 * This replaces the webpack-based auto-registration system.
 */

import applicationMenuItemCompositeInjectable from "./application-menu-item-composite.injectable";
import applicationMenuItemRegistratorInjectable from "./application-menu-item-registrator.injectable";
import applicationMenuItemsInjectable from "./application-menu-items.injectable";
import applicationMenuReactivityInjectable from "./application-menu-reactivity.injectable";
import { registerInjectables as registerMenuItemsInjectables } from "./menu-items/register-injectables";
import populateApplicationMenuInjectable from "./populate-application-menu.injectable";
import startApplicationMenuInjectable from "./start-application-menu.injectable";
import stopApplicationMenuInjectable from "./stop-application-menu.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(applicationMenuItemCompositeInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(applicationMenuItemRegistratorInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(applicationMenuItemsInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(applicationMenuReactivityInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(populateApplicationMenuInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(startApplicationMenuInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(stopApplicationMenuInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerMenuItemsInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
