/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import aiPreferenceBlockInjectable from "./ai-preference-block.injectable";
import aiPreferencePageInjectable from "./ai-preference-page.injectable";
import aiPreferenceTabInjectable from "./ai-preference-tab.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(aiPreferenceBlockInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(aiPreferencePageInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(aiPreferenceTabInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
