/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import navigateToServiceAccountsInjectable from "./navigate-to-service-accounts.injectable";
import serviceAccountsRouteInjectable from "./service-accounts-route.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(navigateToServiceAccountsInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(serviceAccountsRouteInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
