/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import kubeconfigDialogClusterFrameChildComponentInjectable from "./kubeconfig-dialog-cluster-frame-child-component.injectable";
import openKubeconfigDialogInjectable from "./open.injectable";
import openServiceAccountKubeConfigDialogInjectable from "./open-service-account-kube-config-dialog.injectable";
import kubeconfigDialogStateInjectable from "./state.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(kubeconfigDialogClusterFrameChildComponentInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(kubeconfigDialogStateInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(openKubeconfigDialogInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(openServiceAccountKubeConfigDialogInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
