/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import { notificationsClusterFrameChildComponentInjectable } from "./notifications-cluster-frame-child-component.injectable";
import { notificationsRootFrameChildComponentInjectable } from "./notifications-root-frame-child-component.injectable";
import { notificationsStoreInjectable } from "./notifications-store.injectable";
import { showCheckedErrorNotificationInjectable } from "./show-checked-error.injectable";
import { showErrorNotificationInjectable } from "./show-error-notification.injectable";
import { showInfoNotificationInjectable } from "./show-info-notification.injectable";
import { showShortInfoNotificationInjectable } from "./show-short-info.injectable";
import { showSuccessNotificationInjectable } from "./show-success-notification.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(notificationsClusterFrameChildComponentInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(notificationsRootFrameChildComponentInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(notificationsStoreInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(showCheckedErrorNotificationInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(showErrorNotificationInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(showInfoNotificationInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(showShortInfoNotificationInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(showSuccessNotificationInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
