/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import legacyOnChannelListenInjectable from "./legacy-channel-listen.injectable";
import listNamespacesForbiddenHandlerInjectable from "./list-namespaces-forbidden-handler.injectable";
import registerIpcListenersInjectable from "./register-ipc-listeners.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(legacyOnChannelListenInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(listNamespacesForbiddenHandlerInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(registerIpcListenersInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
