/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import limitRangesRouteComponentInjectable from "./limit-ranges-route-component.injectable";
import limitRangesSidebarItemInjectable from "./limit-ranges-sidebar-item.injectable";
import limitRangeStoreInjectable from "./store.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(limitRangeStoreInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(limitRangesRouteComponentInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(limitRangesSidebarItemInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
