/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file imports and registers all injectables from subdirectories.
 * This replaces the webpack-based auto-registration system.
 */

import { registerInjectables as registerAppEventBusInjectables } from "./app-event-bus/register-injectables";
import { registerInjectables as registerAppPathsInjectables } from "./app-paths/register-injectables";
import { registerInjectables as registerCatalogInjectables } from "./catalog/register-injectables";
import { registerInjectables as registerCatalogEntitiesInjectables } from "./catalog-entities/register-injectables";
import { registerInjectables as registerCertificateInjectables } from "./certificate/register-injectables";
import { registerInjectables as registerClusterInjectables } from "./cluster/register-injectables";
import clusterFramesInjectable from "./cluster-frames.injectable";
import { registerInjectables as registerDirectoryForLensLocalStorageInjectables } from "./directory-for-lens-local-storage/register-injectables";
import { registerInjectables as registerFetchInjectables } from "./fetch/register-injectables";
import { registerInjectables as registerFrontEndRoutingInjectables } from "./front-end-routing/register-injectables";
import { registerInjectables as registerFsInjectables } from "./fs/register-injectables";
import { registerInjectables as registerGetConfigurationFileModelInjectables } from "./get-configuration-file-model/register-injectables";
import { registerInjectables as registerIpcInjectables } from "./ipc/register-injectables";
import { registerInjectables as registerK8sInjectables } from "./k8s/register-injectables";
import { registerInjectables as registerK8sApiInjectables } from "./k8s-api/register-injectables";
import { registerInjectables as registerKubeHelpersInjectables } from "./kube-helpers/register-injectables";
import logErrorInjectable from "./log-error.injectable";
import { registerInjectables as registerOsInjectables } from "./os/register-injectables";
import { registerInjectables as registerPathInjectables } from "./path/register-injectables";
import { registerInjectables as registerUtilsInjectables } from "./utils/register-injectables";
import { registerInjectables as registerVarsInjectables } from "./vars/register-injectables";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(clusterFramesInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(logErrorInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerAppEventBusInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerAppPathsInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerCatalogInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerCatalogEntitiesInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerCertificateInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerClusterInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerDirectoryForLensLocalStorageInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerFetchInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerFrontEndRoutingInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerFsInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerGetConfigurationFileModelInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerIpcInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerK8sInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerK8sApiInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerKubeHelpersInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerOsInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerPathInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerUtilsInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerVarsInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
