/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import downloadBinaryInjectable from "./download-binary.injectable";
import nodeFetchChannelListenerInjectable from "./download-binary-channel-listener.injectable";
import downloadJsonInjectable from "./download-json.injectable";
import nodeFetchChannelListenerInjectable2 from "./download-json-channel-listener-copy.injectable";
import httpsAgentInjectable from "./https-agent.injectable";
import lensFetchInjectable from "./lens-fetch.injectable";
import proxyFetchInjectable from "./proxy-fetch.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(downloadBinaryInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(downloadJsonInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(httpsAgentInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(lensFetchInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(nodeFetchChannelListenerInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(nodeFetchChannelListenerInjectable2);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(proxyFetchInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
