/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import requestClusterMetricsByNodeNamesInjectable from "./request-cluster-metrics-by-node-names.injectable";
import requestIngressMetricsInjectable from "./request-ingress-metrics.injectable";
import requestMetricsInjectable from "./request-metrics.injectable";
import requestAllNodeMetricsInjectable from "./request-metrics-for-all-nodes.injectable";
import requestPersistentVolumeClaimMetricsInjectable from "./request-persistent-volume-claim-metrics.injectable";
import requestPodMetricsInjectable from "./request-pod-metrics.injectable";
import requestPodMetricsForDaemonSetsInjectable from "./request-pod-metrics-for-daemon-sets.injectable";
import requestPodMetricsForDeploymentsInjectable from "./request-pod-metrics-for-deployments.injectable";
import requestPodMetricsForJobsInjectable from "./request-pod-metrics-for-jobs.injectable";
import requestPodMetricsForReplicaSetsInjectable from "./request-pod-metrics-for-replica-sets.injectable";
import requestPodMetricsForStatefulSetsInjectable from "./request-pod-metrics-for-stateful-sets.injectable";
import requestPodMetricsInNamespaceInjectable from "./request-pod-metrics-in-namespace.injectable";
import requestMetricsProvidersInjectable from "./request-providers.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(requestAllNodeMetricsInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(requestClusterMetricsByNodeNamesInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(requestIngressMetricsInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(requestMetricsInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(requestMetricsProvidersInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(requestPersistentVolumeClaimMetricsInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(requestPodMetricsForDaemonSetsInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(requestPodMetricsForDeploymentsInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(requestPodMetricsForJobsInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(requestPodMetricsForReplicaSetsInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(requestPodMetricsForStatefulSetsInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(requestPodMetricsInNamespaceInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(requestPodMetricsInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
