/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file imports and registers all injectables from subdirectories.
 * This replaces the webpack-based auto-registration system.
 */

import extensionDiscoveryInjectable from "./extension-discovery.injectable";
import { registerInjectables as registerIsCompatibleExtensionInjectables } from "./is-compatible-extension/register-injectables";
import stopWatchingExtensionsOnQuitInjectable from "./stop-watching-extensions-on-quit.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(extensionDiscoveryInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(stopWatchingExtensionsOnQuitInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerIsCompatibleExtensionInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
