/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import clusterFrameHandlerInjectable from "./cluster-frame-handler.injectable";
import clusterManagerRootFrameChildComponentInjectable from "./cluster-manager-root-frame-child-component.injectable";
import clusterViewRouteComponentInjectable from "./cluster-view-route-component.injectable";
import clusterViewRouteParametersInjectable from "./cluster-view-route-parameters.injectable";
import emitClusterVisibilityInjectable from "./emit-cluster-visibility.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(clusterFrameHandlerInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(clusterManagerRootFrameChildComponentInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(clusterViewRouteComponentInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(clusterViewRouteParametersInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(emitClusterVisibilityInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
