/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file imports and registers all injectables from subdirectories.
 * This replaces the webpack-based auto-registration system.
 */

import { registerInjectables as registerAttemptInstallInjectables } from "./attempt-install/register-injectables";
import attemptInstallByInfoInjectable from "./attempt-install-by-info.injectable";
import attemptInstallsInjectable from "./attempt-installs.injectable";
import confirmUninstallExtensionInjectable from "./confirm-uninstall-extension.injectable";
import disableExtensionInjectable from "./disable-extension.injectable";
import enableExtensionInjectable from "./enable-extension.injectable";
import extensionsRouteComponentInjectable from "./extensions-route-component.injectable";
import { registerInjectables as registerGetBaseRegistryUrlInjectables } from "./get-base-registry-url/register-injectables";
import installExtensionFromInputInjectable from "./install-extension-from-input.injectable";
import installFromSelectFileDialogInjectable from "./install-from-select-file-dialog.injectable";
import installOnDropInjectable from "./install-on-drop.injectable";
import { registerInjectables as registerReadFileNotifyInjectables } from "./read-file-notify/register-injectables";
import uninstallExtensionInjectable from "./uninstall-extension.injectable";
import { registerInjectables as registerUserExtensionsInjectables } from "./user-extensions/register-injectables";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(attemptInstallByInfoInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(attemptInstallsInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(confirmUninstallExtensionInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(disableExtensionInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(enableExtensionInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(extensionsRouteComponentInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(installExtensionFromInputInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(installFromSelectFileDialogInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(installOnDropInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(uninstallExtensionInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerAttemptInstallInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerGetBaseRegistryUrlInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerReadFileNotifyInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerUserExtensionsInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
