name: COPR build

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    container: fedora:45

    steps:
      - name: Install build dependencies
        run: dnf --assumeyes install git python3-pip

      - name: Install COPR CLI
        run: python3 -m pip install copr-cli

      - name: Configure COPR CLI
        env:
          COPR_LOGIN: ${{ secrets.COPR_LOGIN }}
          COPR_TOKEN: ${{ secrets.COPR_TOKEN }}
          COPR_USERNAME: ${{ secrets.COPR_USERNAME }}
        run: |
          mkdir -p ~/.config
          cat > ~/.config/copr <<EOF
          [copr-cli]
          login = $COPR_LOGIN
          username = $COPR_USERNAME
          token = $COPR_TOKEN
          copr_url = https://copr.fedorainfracloud.org
          EOF

      - name: Configure COPR chroots
        run: |
          copr-cli modify ok8219/Freelens \
            --chroot fedora-43-x86_64 \
            --chroot fedora-44-x86_64 \
            --chroot fedora-45-x86_64 \
            --chroot fedora-rawhide-x86_64

      - name: Submit COPR SCM build
        run: |
          copr-cli buildscm ok8219/Freelens \
            --clone-url https://github.com/kappa8219/freelens-copr.git \
            --commit main \
            --subdir .copr \
            --spec ../freelens.spec \
            --method make_srpm \
            --enable-net on \
            --nowait \
            -r fedora-43-x86_64 \
            -r fedora-44-x86_64 \
            -r fedora-45-x86_64 \
            -r fedora-rawhide-x86_64
