/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import cronJobsRouteInjectable from "./cron-jobs-route.injectable";
import navigateToCronJobsInjectable from "./navigate-to-cron-jobs.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(cronJobsRouteInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(navigateToCronJobsInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
