/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file imports and registers all injectables from subdirectories.
 * This replaces the webpack-based auto-registration system.
 */

import chatStreamListenerInjectable from "./chat-stream-listener.injectable";
import { registerInjectables as registerComponentsInjectables } from "./components/register-injectables";
import { registerInjectables as registerPreferencesInjectables } from "./preferences/register-injectables";
import { registerInjectables as registerStoresInjectables } from "./stores/register-injectables";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(chatStreamListenerInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerComponentsInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerPreferencesInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    registerStoresInjectables(di);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
