/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import navigateToVerticalPodAutoscalersInjectable from "./navigate-to-vertical-pod-autoscalers.injectable";
import verticalPodAutoscalersRouteInjectable from "./vertical-pod-autoscalers-route.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(navigateToVerticalPodAutoscalersInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(verticalPodAutoscalersRouteInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
