/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-explicit-di-registration.mjs
 *
 * This file explicitly registers all injectables for this package.
 * This replaces the webpack-based auto-registration system.
 */

import kubectlApplyAllChannelHandlerInjectable from "./apply-all-handler.injectable";
import kubectlBinaryNameInjectable from "./binary-name.injectable";
import bundledKubectlBinaryPathInjectable from "./bundled-binary-path.injectable";
import bundledKubectlInjectable from "./bundled-kubectl.injectable";
import createKubectlInjectable from "./create-kubectl.injectable";
import kubectlDeleteAllChannelHandlerInjectable from "./delete-all-handler.injectable";
import kubectlApplyAllInjectable from "./kubectl-apply-all.injectable";
import kubectlDeleteAllInjectable from "./kubectl-delete-all.injectable";
import kubectlDownloadingNormalizedArchInjectable from "./normalized-arch.injectable";
import kubectlVersionMapInjectable from "./version-map.injectable";

import type { DiContainerForInjection } from "@ogre-tools/injectable";

export function registerInjectables(di: DiContainerForInjection): void {
  try {
    di.register(bundledKubectlBinaryPathInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(bundledKubectlInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(createKubectlInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(kubectlApplyAllChannelHandlerInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(kubectlApplyAllInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(kubectlBinaryNameInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(kubectlDeleteAllChannelHandlerInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(kubectlDeleteAllInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(kubectlDownloadingNormalizedArchInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
  try {
    di.register(kubectlVersionMapInjectable);
  } catch (e) {
    /* Ignore duplicate registration */
  }
}
